version: '3.7'
services:

#  redis:
#    container_name: redis
#    image: redis:5
#    ports:
#      - 6379:6379
#    networks:
#      - webnet
#  traefik:
#    image: "traefik:v2.0.0"
#    command:
#      - --entrypoints.web.address=:80
#      - --entrypoints.websecure.address=:443
#      - --providers.docker
#      - --api
#    ports:
#      - "80:80"
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock:ro"
#    labels:
#      # global redirect to https
#      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
#      - "traefik.http.routers.http-catchall.entrypoints=web"
#      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
#
#      # middleware redirect
#      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
#    depends_on:
#      - redis
  crm-hub:
    container_name: crm-hub
    working_dir: /usr/src/app
    build:
      context: ./hub
      dockerfile: Dockerfile
    env_file:
      - ./hub/api/.env
    networks:
      - webnet
  crm-dev:
    container_name: crm-dev
    working_dir: /usr/src/app
    build:
      context: ./dev
      dockerfile: Dockerfile
    env_file:
      - ./dev/api/.env
    networks:
      - webnet
    depends_on:
      - crm-hub
      - crm-system
      - crm-proxy
#  crm-pages:
#    container_name: crm-pages
#    working_dir: /usr/src/app
#    build:
#      context: ./pages
#      dockerfile: Dockerfile
#    env_file:
#      - ./pages/api/.env
#    networks:
#      - webnet
#    depends_on:
#      - redis
#      - crm-hub
#      - crm-system
  crm-system:
    container_name: crm-system
    working_dir: /usr/src/app
    build:
      context: ./system
      dockerfile: Dockerfile
    env_file:
      - ./system/api/.env
    networks:
      - webnet
    depends_on:
      - crm-hub
  crm-proxy:
    container_name: crm-proxy
    working_dir: /usr/src/app
    build:
      context: ./proxy
      dockerfile: Dockerfile
    env_file:
      - ./proxy/api/.env
    networks:
      - webnet
    ports:
      - 30443:30443
    depends_on:
      - crm-hub
      - crm-system
networks:
  webnet: