version: '3.7'
services:
  nginx-redirect-http-to-https:
    container_name: nginx-redirect-http-to-https
      working_dir: /usr/src/app
      build:
        context: ./helpers/nginx-redirect-http-to-https
        dockerfile: Dockerfile
      depends_on:
        - redis
  redis:
    container_name: redis
    image: redis:5
    ports:
      - 6379:6379
    networks:
      - webnet
#  crm-hub:
#    container_name: crm-hub
#    working_dir: /usr/src/app
#    build:
#      context: ./hub
#      dockerfile: Dockerfile
#    env_file:
#      - ./hub/api/.env
#    networks:
#      - webnet
#    depends_on:
#      - redis
#  crm-dev:
#    container_name: crm-dev
#    working_dir: /usr/src/app
#    build:
#      context: ./dev
#      dockerfile: Dockerfile
#    env_file:
#      - ./dev/api/.env
#    networks:
#      - webnet
#    depends_on:
#      - redis
#      - crm-hub
#      - crm-system
#  crm-pages:
#    container_name: crm-pages
#    working_dir: /usr/src/app
#    build:
#      context: ./pages
#      dockerfile: Dockerfile
#    env_file:
#      - ./pages/api/.env
#    networks:
#      - webnet
#    depends_on:
#      - redis
#      - crm-hub
#      - crm-system
#  crm-system:
#    container_name: crm-system
#    working_dir: /usr/src/app
#    build:
#      context: ./system
#      dockerfile: Dockerfile
#    env_file:
#      - ./system/api/.env
#    networks:
#      - webnet
#    ports:
#      - 80:80
#    depends_on:
#      - redis
#      - crm-hub
    crm-proxy:
      container_name: crm-proxy
      working_dir: /usr/src/app
      build:
        context: ./proxy
        dockerfile: Dockerfile
      env_file:
        - ./proxy/api/.env
      networks:
        - webnet
      ports:
        - 3080:3080
      depends_on:
        - redis
        - crm-hub
networks:
  webnet: