--
-- PostgreSQL database dump
--

-- Dumped from database version 11.14
-- Dumped by pg_dump version 11.14

-- Started on 2022-02-28 07:39:15 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3161 (class 1262 OID 16385)
-- Name: agency; Type: DATABASE; Schema: -; Owner: cms
--

SELECT 'CREATE DATABASE agency WITH TEMPLATE = template0 ENCODING = ''UTF8'' LC_COLLATE = ''en_US.utf8'' LC_CTYPE = ''en_US.utf8'''
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'agency')\gexec

ALTER DATABASE agency OWNER TO cms;

\connect agency

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 219 (class 1259 OID 16724)
-- Name: AirlineCabinModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."AirlineCabinModels" (
    "Id" integer NOT NULL,
    "Label" character varying(255),
    "Description" text,
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."AirlineCabinModels" OWNER TO cms;

--
-- TOC entry 218 (class 1259 OID 16722)
-- Name: AirlineCabinModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."AirlineCabinModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AirlineCabinModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 201 (class 1259 OID 16600)
-- Name: BookingItemModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."BookingItemModels" (
    "Id" integer NOT NULL,
    "Type" integer,
    "Status" integer,
    "Label" integer,
    "Description" integer,
    "StartDate" text,
    "EndDate" text,
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."BookingItemModels" OWNER TO cms;

--
-- TOC entry 200 (class 1259 OID 16598)
-- Name: BookingItemModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."BookingItemModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."BookingItemModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 203 (class 1259 OID 16610)
-- Name: BookingItemStatusModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."BookingItemStatusModels" (
    "Id" integer NOT NULL,
    "Label" character varying(255),
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."BookingItemStatusModels" OWNER TO cms;

--
-- TOC entry 202 (class 1259 OID 16608)
-- Name: BookingItemStatusModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."BookingItemStatusModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."BookingItemStatusModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 205 (class 1259 OID 16617)
-- Name: BookingItemTypeModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."BookingItemTypeModels" (
    "Id" integer NOT NULL,
    other character varying(255),
    package character varying(255),
    bus character varying(255),
    flight character varying(255),
    transfer character varying(255),
    hotel character varying(255),
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."BookingItemTypeModels" OWNER TO cms;

--
-- TOC entry 204 (class 1259 OID 16615)
-- Name: BookingItemTypeModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."BookingItemTypeModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."BookingItemTypeModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 207 (class 1259 OID 16628)
-- Name: BookingModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."BookingModels" (
    "Id" integer NOT NULL,
    "Reference" integer,
    "Created" text,
    "StartDate" text,
    "EndDate" text,
    "BalanceDueDate" text,
    "InvoiceCurrency" character varying(255),
    "Price" character varying(255),
    "Items" character varying(255),
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."BookingModels" OWNER TO cms;

--
-- TOC entry 206 (class 1259 OID 16626)
-- Name: BookingModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."BookingModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."BookingModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 16648)
-- Name: BookingOptionFlightModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."BookingOptionFlightModels" (
    "Id" integer NOT NULL,
    "OutboundIndex" integer,
    "InboundIndex" integer,
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."BookingOptionFlightModels" OWNER TO cms;

--
-- TOC entry 208 (class 1259 OID 16646)
-- Name: BookingOptionFlightModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."BookingOptionFlightModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."BookingOptionFlightModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 16655)
-- Name: BookingOptionHotelModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."BookingOptionHotelModels" (
    "Id" integer NOT NULL,
    "MealPlanIndex" integer,
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."BookingOptionHotelModels" OWNER TO cms;

--
-- TOC entry 210 (class 1259 OID 16653)
-- Name: BookingOptionHotelModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."BookingOptionHotelModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."BookingOptionHotelModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 16663)
-- Name: BookingOptionPackageModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."BookingOptionPackageModels" (
    "Id" integer NOT NULL,
    "ExtraComponents" character varying(255),
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."BookingOptionPackageModels" OWNER TO cms;

--
-- TOC entry 212 (class 1259 OID 16661)
-- Name: BookingOptionPackageModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."BookingOptionPackageModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."BookingOptionPackageModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16774)
-- Name: DetailedDescriptionModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."DetailedDescriptionModels" (
    "Id" integer NOT NULL,
    "Label" character varying(255),
    "Text" text,
    "Index" smallint,
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."DetailedDescriptionModels" OWNER TO cms;

--
-- TOC entry 228 (class 1259 OID 16772)
-- Name: DetailedDescriptionModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."DetailedDescriptionModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DetailedDescriptionModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16784)
-- Name: DiscountInfoModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."DiscountInfoModels" (
    "Id" integer NOT NULL,
    "Label" character varying(255),
    "Text" text,
    "BookingFrom" timestamp with time zone,
    "BookingTo" timestamp with time zone,
    "TravelFrom" timestamp with time zone,
    "TravelTo" timestamp with time zone,
    "Percent" timestamp with time zone,
    "Value" double precision,
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."DiscountInfoModels" OWNER TO cms;

--
-- TOC entry 230 (class 1259 OID 16782)
-- Name: DiscountInfoModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."DiscountInfoModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DiscountInfoModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16794)
-- Name: ExtraComponentModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."ExtraComponentModels" (
    "Id" integer NOT NULL,
    "Label" character varying(255),
    "Description" text,
    "Price" double precision,
    "IsOptional" smallint,
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."ExtraComponentModels" OWNER TO cms;

--
-- TOC entry 232 (class 1259 OID 16792)
-- Name: ExtraComponentModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."ExtraComponentModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ExtraComponentModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 197 (class 1259 OID 16579)
-- Name: FileInfoModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."FileInfoModels" (
    "Id" integer NOT NULL,
    "MimeType" character varying(255),
    "Name" character varying(255),
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."FileInfoModels" OWNER TO cms;

--
-- TOC entry 196 (class 1259 OID 16577)
-- Name: FileInfoModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."FileInfoModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."FileInfoModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 199 (class 1259 OID 16589)
-- Name: GenderModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."GenderModels" (
    "Id" integer NOT NULL,
    "Label" character varying(255),
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."GenderModels" OWNER TO cms;

--
-- TOC entry 198 (class 1259 OID 16587)
-- Name: GenderModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."GenderModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."GenderModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16744)
-- Name: GeographyModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."GeographyModels" (
    "Id" integer NOT NULL,
    "Name" character varying(255),
    "IntName" character varying(255),
    "ChildLabel" character varying(255),
    "Description" text,
    "Image" text,
    "ParentId" integer,
    active smallint,
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."GeographyModels" OWNER TO cms;

--
-- TOC entry 222 (class 1259 OID 16742)
-- Name: GeographyModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."GeographyModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."GeographyModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16754)
-- Name: HotelModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."HotelModels" (
    "Id" integer NOT NULL,
    "Source" character varying(255),
    "SourceId" integer,
    "Code" character varying(255),
    "Name" character varying(255),
    "Class" integer,
    "Description" text,
    "WebDescription" text,
    "Address" character varying(255),
    "ZIP" character varying(255),
    "Phone" character varying(255),
    "Fax" character varying(255),
    "Location" integer,
    "URL" character varying(255),
    "Latitude" double precision,
    "Longitude" double precision,
    "RoomCategories" character varying(255),
    "Images" character varying(255),
    "DetailedDescriptions" text,
    "HotelTheme" character varying(255),
    "HotelAmenities" character varying(255),
    "RoomAmenities" character varying(255),
    "ExtraClass" character varying(255),
    "UseIndividually" smallint,
    "UseOnPackages" smallint,
    "PropertyType" character varying(255),
    active smallint,
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."HotelModels" OWNER TO cms;

--
-- TOC entry 224 (class 1259 OID 16752)
-- Name: HotelModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."HotelModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."HotelModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16734)
-- Name: LegModules; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."LegModules" (
    "Id" integer NOT NULL,
    "From" character varying(255),
    "To" character varying(255),
    "Departure" timestamp with time zone,
    "Arrival" timestamp with time zone,
    "Airline" character varying(255),
    "FlightNo" character varying(255),
    "Class" character varying(255),
    "DepTerminal" character varying(255),
    "ArrTerminal" character varying(255),
    "DepGate" character varying(255),
    "ArrGate" character varying(255),
    "FlightTime" character varying(255),
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."LegModules" OWNER TO cms;

--
-- TOC entry 220 (class 1259 OID 16732)
-- Name: LegModules_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."LegModules" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."LegModules_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16804)
-- Name: MealPlanModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."MealPlanModels" (
    "Id" integer NOT NULL,
    "Label" character varying(255),
    "Price" character varying(255),
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."MealPlanModels" OWNER TO cms;

--
-- TOC entry 234 (class 1259 OID 16802)
-- Name: MealPlanModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."MealPlanModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MealPlanModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16814)
-- Name: PackageInfoModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."PackageInfoModels" (
    "Id" integer NOT NULL,
    "Name" character varying(255),
    "IsTour" smallint,
    "IsBus" smallint,
    "IsFlight" smallint,
    "Currency" character varying(255),
    "Duration" integer,
    "OutboundTransportDuration" integer,
    "Description" text,
    "IncludedServices" text,
    "NotIncludedServices" text,
    "Destination" integer,
    "HotelSource" integer,
    "Hotel" integer,
    "DepartureDates" character varying(255),
    "DeparturePoints" character varying(255),
    "PriceSets" character varying(255),
    "DetailedDescriptions" text,
    "FareType" character varying(255),
    active smallint,
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."PackageInfoModels" OWNER TO cms;

--
-- TOC entry 236 (class 1259 OID 16812)
-- Name: PackageInfoModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."PackageInfoModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PackageInfoModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16677)
-- Name: PaxInfoModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."PaxInfoModels" (
    "Id" integer NOT NULL,
    "Title" character varying(255),
    "FirstName" character varying(255),
    "LastName" character varying(255),
    "Type" character varying(255),
    "BirthDate" timestamp with time zone,
    "Gender" character varying(255),
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."PaxInfoModels" OWNER TO cms;

--
-- TOC entry 214 (class 1259 OID 16675)
-- Name: PaxInfoModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."PaxInfoModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PaxInfoModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16702)
-- Name: PaxTypeModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."PaxTypeModels" (
    "Id" integer NOT NULL,
    "Label" character varying(255),
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."PaxTypeModels" OWNER TO cms;

--
-- TOC entry 216 (class 1259 OID 16700)
-- Name: PaxTypeModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."PaxTypeModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PaxTypeModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 16824)
-- Name: PriceInfoModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."PriceInfoModels" (
    "Id" integer NOT NULL,
    "Gross" double precision,
    "Commission" double precision,
    "VAT" double precision,
    "Tax" double precision,
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."PriceInfoModels" OWNER TO cms;

--
-- TOC entry 238 (class 1259 OID 16822)
-- Name: PriceInfoModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."PriceInfoModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PriceInfoModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16831)
-- Name: PriceSetModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."PriceSetModels" (
    "Id" integer NOT NULL,
    "Label" character varying(255),
    "Description" text,
    "ValidFrom" timestamp with time zone,
    "ValidTo" timestamp with time zone,
    "TravelFrom" timestamp with time zone,
    "TravelTo" timestamp with time zone,
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."PriceSetModels" OWNER TO cms;

--
-- TOC entry 240 (class 1259 OID 16829)
-- Name: PriceSetModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."PriceSetModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PriceSetModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16764)
-- Name: RoomCategoryModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."RoomCategoryModels" (
    "Id" integer NOT NULL,
    "Name" character varying(255),
    "Description" text,
    "Images" text,
    active smallint,
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."RoomCategoryModels" OWNER TO cms;

--
-- TOC entry 226 (class 1259 OID 16762)
-- Name: RoomCategoryModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."RoomCategoryModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RoomCategoryModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 16841)
-- Name: RoomModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."RoomModels" (
    "Id" integer NOT NULL,
    "Adults" integer,
    "ChildAges" character varying(255),
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."RoomModels" OWNER TO cms;

--
-- TOC entry 242 (class 1259 OID 16839)
-- Name: RoomModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."RoomModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RoomModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 16848)
-- Name: SpecialOfferModels; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."SpecialOfferModels" (
    "Id" integer NOT NULL,
    "Code" character varying(255),
    "Label" character varying(255),
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."SpecialOfferModels" OWNER TO cms;

--
-- TOC entry 244 (class 1259 OID 16846)
-- Name: SpecialOfferModels_Id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."SpecialOfferModels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SpecialOfferModels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3008 (class 2606 OID 16731)
-- Name: AirlineCabinModels AirlineCabinModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."AirlineCabinModels"
    ADD CONSTRAINT "AirlineCabinModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 2990 (class 2606 OID 16607)
-- Name: BookingItemModels BookingItemModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."BookingItemModels"
    ADD CONSTRAINT "BookingItemModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 2992 (class 2606 OID 16614)
-- Name: BookingItemStatusModels BookingItemStatusModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."BookingItemStatusModels"
    ADD CONSTRAINT "BookingItemStatusModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 2994 (class 2606 OID 16625)
-- Name: BookingItemTypeModels BookingItemTypeModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."BookingItemTypeModels"
    ADD CONSTRAINT "BookingItemTypeModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 2996 (class 2606 OID 16635)
-- Name: BookingModels BookingModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."BookingModels"
    ADD CONSTRAINT "BookingModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 2998 (class 2606 OID 16652)
-- Name: BookingOptionFlightModels BookingOptionFlightModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."BookingOptionFlightModels"
    ADD CONSTRAINT "BookingOptionFlightModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3000 (class 2606 OID 16659)
-- Name: BookingOptionHotelModels BookingOptionHotelModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."BookingOptionHotelModels"
    ADD CONSTRAINT "BookingOptionHotelModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3002 (class 2606 OID 16667)
-- Name: BookingOptionPackageModels BookingOptionPackageModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."BookingOptionPackageModels"
    ADD CONSTRAINT "BookingOptionPackageModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3018 (class 2606 OID 16781)
-- Name: DetailedDescriptionModels DetailedDescriptionModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."DetailedDescriptionModels"
    ADD CONSTRAINT "DetailedDescriptionModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3020 (class 2606 OID 16791)
-- Name: DiscountInfoModels DiscountInfoModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."DiscountInfoModels"
    ADD CONSTRAINT "DiscountInfoModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3022 (class 2606 OID 16801)
-- Name: ExtraComponentModels ExtraComponentModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."ExtraComponentModels"
    ADD CONSTRAINT "ExtraComponentModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 2986 (class 2606 OID 16586)
-- Name: FileInfoModels FileInfoModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."FileInfoModels"
    ADD CONSTRAINT "FileInfoModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 2988 (class 2606 OID 16593)
-- Name: GenderModels GenderModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."GenderModels"
    ADD CONSTRAINT "GenderModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3012 (class 2606 OID 16751)
-- Name: GeographyModels GeographyModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."GeographyModels"
    ADD CONSTRAINT "GeographyModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3014 (class 2606 OID 16761)
-- Name: HotelModels HotelModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."HotelModels"
    ADD CONSTRAINT "HotelModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3010 (class 2606 OID 16741)
-- Name: LegModules LegModules_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."LegModules"
    ADD CONSTRAINT "LegModules_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3024 (class 2606 OID 16811)
-- Name: MealPlanModels MealPlanModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."MealPlanModels"
    ADD CONSTRAINT "MealPlanModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3026 (class 2606 OID 16821)
-- Name: PackageInfoModels PackageInfoModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."PackageInfoModels"
    ADD CONSTRAINT "PackageInfoModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3004 (class 2606 OID 16684)
-- Name: PaxInfoModels PaxInfoModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."PaxInfoModels"
    ADD CONSTRAINT "PaxInfoModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3006 (class 2606 OID 16706)
-- Name: PaxTypeModels PaxTypeModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."PaxTypeModels"
    ADD CONSTRAINT "PaxTypeModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3028 (class 2606 OID 16828)
-- Name: PriceInfoModels PriceInfoModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."PriceInfoModels"
    ADD CONSTRAINT "PriceInfoModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3030 (class 2606 OID 16838)
-- Name: PriceSetModels PriceSetModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."PriceSetModels"
    ADD CONSTRAINT "PriceSetModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3016 (class 2606 OID 16771)
-- Name: RoomCategoryModels RoomCategoryModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."RoomCategoryModels"
    ADD CONSTRAINT "RoomCategoryModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3032 (class 2606 OID 16845)
-- Name: RoomModels RoomModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."RoomModels"
    ADD CONSTRAINT "RoomModels_pkey" PRIMARY KEY ("Id");


--
-- TOC entry 3034 (class 2606 OID 16855)
-- Name: SpecialOfferModels SpecialOfferModels_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."SpecialOfferModels"
    ADD CONSTRAINT "SpecialOfferModels_pkey" PRIMARY KEY ("Id");


-- Completed on 2022-02-28 07:39:15 UTC

--
-- PostgreSQL database dump complete
--

