--
-- PostgreSQL database dump
--

-- Dumped from database version 11.14
-- Dumped by pg_dump version 11.14

-- Started on 2022-02-27 11:10:02 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- HOW DO I CHANGE THIS TO BE A VARIABLE --
\connect main

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 196 (class 1259 OID 16385)
-- Name: AdminThemes; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."AdminThemes" (
    id integer NOT NULL,
    title character varying(255),
    "isDefault" smallint,
    data text,
    thumbnail text,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."AdminThemes" OWNER TO cms;

--
-- TOC entry 197 (class 1259 OID 16391)
-- Name: AdminThemes_id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."AdminThemes" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AdminThemes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 198 (class 1259 OID 16393)
-- Name: Auths; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."Auths" (
    id integer NOT NULL,
    fname character varying(255),
    lname character varying(255),
    fullname character varying(255),
    email character varying(255),
    password character varying(255),
    active integer,
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."Auths" OWNER TO cms;

--
-- TOC entry 199 (class 1259 OID 16399)
-- Name: Auths_id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."Auths" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Auths_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 200 (class 1259 OID 16401)
-- Name: Categories; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."Categories" (
    id integer NOT NULL,
    title character varying(255),
    description text,
    "backgroundImage" character varying(255),
    "parentId" integer,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."Categories" OWNER TO cms;

--
-- TOC entry 201 (class 1259 OID 16407)
-- Name: Categories_id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."Categories" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 202 (class 1259 OID 16409)
-- Name: DashboardBoxes; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."DashboardBoxes" (
    id integer NOT NULL,
    title character varying(255),
    module character varying(255),
    width smallint,
    height smallint,
    x smallint,
    y smallint,
    scrollbars smallint,
    "fontSize" smallint,
    "fontFamily" character varying(255),
    "textColor" character varying(255),
    "borderWidth" smallint,
    "borderColor" character varying(255),
    "borderRadius" smallint,
    "bgColor" character varying(255),
    "moduleOptions" text
);


ALTER TABLE public."DashboardBoxes" OWNER TO cms;

--
-- TOC entry 203 (class 1259 OID 16415)
-- Name: DashboardBoxes_id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."DashboardBoxes" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DashboardBoxes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- TOC entry 206 (class 1259 OID 16425)
-- Name: PageBoxes; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."PageBoxes" (
    id integer NOT NULL,
    title character varying(255),
    module character varying(255),
    data text,
    "moduleOptions" text
);


ALTER TABLE public."PageBoxes" OWNER TO cms;

--
-- TOC entry 207 (class 1259 OID 16431)
-- Name: PageBoxes_id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."PageBoxes" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PageBoxes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 208 (class 1259 OID 16433)
-- Name: PageConfigs; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."PageConfigs" (
    id integer NOT NULL,
    data text
);


ALTER TABLE public."PageConfigs" OWNER TO cms;

--
-- TOC entry 209 (class 1259 OID 16439)
-- Name: PageConfigs_id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."PageConfigs" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PageConfigs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 210 (class 1259 OID 16441)
-- Name: PageToBoxes; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."PageToBoxes" (
    id integer NOT NULL,
    "pageId" integer,
    "boxId" integer,
    x integer,
    y integer,
    "templateUsed" smallint
);


ALTER TABLE public."PageToBoxes" OWNER TO cms;

--
-- TOC entry 211 (class 1259 OID 16444)
-- Name: PageToBoxes_id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."PageToBoxes" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PageToBoxes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 16446)
-- Name: PageToCategories; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."PageToCategories" (
    id integer NOT NULL,
    "pageId" integer,
    "categoryId" integer
);


ALTER TABLE public."PageToCategories" OWNER TO cms;

--
-- TOC entry 213 (class 1259 OID 16449)
-- Name: PageToCategories_id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."PageToCategories" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PageToCategories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 16451)
-- Name: PageToConfigs; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."PageToConfigs" (
    id integer NOT NULL,
    "pageId" integer,
    "configId" integer
);


ALTER TABLE public."PageToConfigs" OWNER TO cms;

--
-- TOC entry 215 (class 1259 OID 16454)
-- Name: PageToConfigs_id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."PageToConfigs" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PageToConfigs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16456)
-- Name: Pages; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."Pages" (
    id integer NOT NULL,
    title character varying(255),
    link character varying(255),
    "isHome" smallint,
    "isTemplate" smallint,
    active smallint,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    "templateId" integer
);


ALTER TABLE public."Pages" OWNER TO cms;

--
-- TOC entry 217 (class 1259 OID 16462)
-- Name: Pages_id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."Pages" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Pages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16516)
-- Name: PublicThemes; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."PublicThemes" (
    id integer NOT NULL,
    title character varying(255),
    "isDefault" smallint,
    data text,
    thumbnail text,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."PublicThemes" OWNER TO cms;

--
-- TOC entry 219 (class 1259 OID 16522)
-- Name: PublicThemes_id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."PublicThemes" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PublicThemes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16524)
-- Name: Settings; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."Settings" (
    id integer NOT NULL,
    data text,
    "isDefault" smallint,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."Settings" OWNER TO cms;

--
-- TOC entry 221 (class 1259 OID 16530)
-- Name: Settings_id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."Settings" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Settings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16532)
-- Name: Users; Type: TABLE; Schema: public; Owner: cms
--

CREATE TABLE public."Users" (
    id integer NOT NULL,
    fname character varying(255),
    lname character varying(255),
    email character varying(255),
    password character varying(255),
    type smallint DEFAULT 4 NOT NULL,
    active integer,
    "accessedAt" timestamp with time zone,
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone
);


ALTER TABLE public."Users" OWNER TO cms;

--
-- TOC entry 223 (class 1259 OID 16539)
-- Name: Users_id_seq; Type: SEQUENCE; Schema: public; Owner: cms
--

ALTER TABLE public."Users" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2915 (class 2606 OID 16558)
-- Name: AdminThemes AdminThemes_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."AdminThemes"
    ADD CONSTRAINT "AdminThemes_pkey" PRIMARY KEY (id);

--
-- TOC entry 3049 (class 2606 OID 16690)
-- Name: Auths Auths_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."Auths"
    ADD CONSTRAINT "Auths_pkey" PRIMARY KEY (id);


--
-- TOC entry 3051 (class 2606 OID 16692)
-- Name: Categories Categories_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "Categories_pkey" PRIMARY KEY (id);


--
-- TOC entry 3054 (class 2606 OID 16694)
-- Name: DashboardBoxes DashboardBoxes_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."DashboardBoxes"
    ADD CONSTRAINT "DashboardBoxes_pkey" PRIMARY KEY (id);

--
-- TOC entry 3061 (class 2606 OID 16698)
-- Name: PageBoxes PageBoxes_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."PageBoxes"
    ADD CONSTRAINT "PageBoxes_pkey" PRIMARY KEY (id);


--
-- TOC entry 3063 (class 2606 OID 16700)
-- Name: PageConfigs PageConfigs_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."PageConfigs"
    ADD CONSTRAINT "PageConfigs_pkey" PRIMARY KEY (id);


--
-- TOC entry 3065 (class 2606 OID 16702)
-- Name: PageToBoxes PageToBoxes_pageId_boxId_key; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."PageToBoxes"
    ADD CONSTRAINT "PageToBoxes_pageId_boxId_key" UNIQUE ("pageId", "boxId");


--
-- TOC entry 3067 (class 2606 OID 16704)
-- Name: PageToBoxes PageToBoxes_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."PageToBoxes"
    ADD CONSTRAINT "PageToBoxes_pkey" PRIMARY KEY (id);


--
-- TOC entry 3071 (class 2606 OID 16706)
-- Name: PageToCategories PageToCategories_pageId_categoryId_key; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."PageToCategories"
    ADD CONSTRAINT "PageToCategories_pageId_categoryId_key" UNIQUE ("pageId", "categoryId");


--
-- TOC entry 3073 (class 2606 OID 16708)
-- Name: PageToCategories PageToCategories_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."PageToCategories"
    ADD CONSTRAINT "PageToCategories_pkey" PRIMARY KEY (id);


--
-- TOC entry 3077 (class 2606 OID 16710)
-- Name: PageToConfigs PageToConfigs_pageId_configId_key; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."PageToConfigs"
    ADD CONSTRAINT "PageToConfigs_pageId_configId_key" UNIQUE ("pageId", "configId");


--
-- TOC entry 3079 (class 2606 OID 16712)
-- Name: PageToConfigs PageToConfigs_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."PageToConfigs"
    ADD CONSTRAINT "PageToConfigs_pkey" PRIMARY KEY (id);


--
-- TOC entry 3082 (class 2606 OID 16714)
-- Name: Pages Pages_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."Pages"
    ADD CONSTRAINT "Pages_pkey" PRIMARY KEY (id);


--
-- TOC entry 3092 (class 2606 OID 16738)
-- Name: PublicThemes PublicThemes_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."PublicThemes"
    ADD CONSTRAINT "PublicThemes_pkey" PRIMARY KEY (id);


--
-- TOC entry 3094 (class 2606 OID 16740)
-- Name: Settings Settings_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."Settings"
    ADD CONSTRAINT "Settings_pkey" PRIMARY KEY (id);


--
-- TOC entry 3228 (class 2606 OID 16872)
-- Name: Users Users_pkey; Type: CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY (id);


--
-- TOC entry 3052 (class 1259 OID 17113)
-- Name: categories_title; Type: INDEX; Schema: public; Owner: cms
--

CREATE INDEX categories_title ON public."Categories" USING btree (title);

CREATE INDEX page_to_boxes_box_id ON public."PageToBoxes" USING btree ("boxId");


--
-- TOC entry 3069 (class 1259 OID 16878)
-- Name: page_to_boxes_page_id; Type: INDEX; Schema: public; Owner: cms
--

CREATE INDEX page_to_boxes_page_id ON public."PageToBoxes" USING btree ("pageId");


--
-- TOC entry 3074 (class 1259 OID 16879)
-- Name: page_to_categories_category_id; Type: INDEX; Schema: public; Owner: cms
--

CREATE INDEX page_to_categories_category_id ON public."PageToCategories" USING btree ("categoryId");


--
-- TOC entry 3075 (class 1259 OID 16880)
-- Name: page_to_categories_page_id; Type: INDEX; Schema: public; Owner: cms
--

CREATE INDEX page_to_categories_page_id ON public."PageToCategories" USING btree ("pageId");


--
-- TOC entry 3080 (class 1259 OID 16881)
-- Name: page_to_configs_page_id; Type: INDEX; Schema: public; Owner: cms
--

CREATE INDEX page_to_configs_page_id ON public."PageToConfigs" USING btree ("pageId");


--
-- TOC entry 3083 (class 1259 OID 17261)
-- Name: pages_active; Type: INDEX; Schema: public; Owner: cms
--

CREATE INDEX pages_active ON public."Pages" USING btree (active);


--
-- TOC entry 3084 (class 1259 OID 17262)
-- Name: pages_created_at; Type: INDEX; Schema: public; Owner: cms
--

CREATE INDEX pages_created_at ON public."Pages" USING btree ("createdAt");


--
-- TOC entry 3085 (class 1259 OID 17259)
-- Name: pages_is_home; Type: INDEX; Schema: public; Owner: cms
--

CREATE INDEX pages_is_home ON public."Pages" USING btree ("isHome");


--
-- TOC entry 3086 (class 1259 OID 17260)
-- Name: pages_is_template; Type: INDEX; Schema: public; Owner: cms
--

CREATE INDEX pages_is_template ON public."Pages" USING btree ("isTemplate");


--
-- TOC entry 3087 (class 1259 OID 17258)
-- Name: pages_link; Type: INDEX; Schema: public; Owner: cms
--

CREATE INDEX pages_link ON public."Pages" USING btree (link);


--
-- TOC entry 3088 (class 1259 OID 17264)
-- Name: pages_template_id; Type: INDEX; Schema: public; Owner: cms
--

CREATE INDEX pages_template_id ON public."Pages" USING btree ("templateId");


--
-- TOC entry 3089 (class 1259 OID 17257)
-- Name: pages_title; Type: INDEX; Schema: public; Owner: cms
--

CREATE INDEX pages_title ON public."Pages" USING btree (title);


--
-- TOC entry 3090 (class 1259 OID 17263)
-- Name: pages_updated_at; Type: INDEX; Schema: public; Owner: cms
--

CREATE INDEX pages_updated_at ON public."Pages" USING btree ("updatedAt");


--
-- TOC entry 3229 (class 1259 OID 17256)
-- Name: users_active; Type: INDEX; Schema: public; Owner: cms
--

CREATE INDEX users_active ON public."Users" USING btree (active);


--
-- TOC entry 3230 (class 1259 OID 17253)
-- Name: users_email; Type: INDEX; Schema: public; Owner: cms
--

CREATE INDEX users_email ON public."Users" USING btree (email);


--
-- TOC entry 3231 (class 1259 OID 17117)
-- Name: users_fname; Type: INDEX; Schema: public; Owner: cms
--

CREATE INDEX users_fname ON public."Users" USING btree (fname);


--
-- TOC entry 3232 (class 1259 OID 17118)
-- Name: users_lname; Type: INDEX; Schema: public; Owner: cms
--

CREATE INDEX users_lname ON public."Users" USING btree (lname);


--
-- TOC entry 3234 (class 2606 OID 17270)
-- Name: PageToBoxes PageToBoxes_boxId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."PageToBoxes"
    ADD CONSTRAINT "PageToBoxes_boxId_fkey" FOREIGN KEY ("boxId") REFERENCES public."PageBoxes"(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3233 (class 2606 OID 17265)
-- Name: PageToBoxes PageToBoxes_pageId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."PageToBoxes"
    ADD CONSTRAINT "PageToBoxes_pageId_fkey" FOREIGN KEY ("pageId") REFERENCES public."Pages"(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3236 (class 2606 OID 17280)
-- Name: PageToCategories PageToCategories_categoryId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."PageToCategories"
    ADD CONSTRAINT "PageToCategories_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES public."Categories"(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3235 (class 2606 OID 17275)
-- Name: PageToCategories PageToCategories_pageId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."PageToCategories"
    ADD CONSTRAINT "PageToCategories_pageId_fkey" FOREIGN KEY ("pageId") REFERENCES public."Pages"(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3238 (class 2606 OID 17290)
-- Name: PageToConfigs PageToConfigs_configId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."PageToConfigs"
    ADD CONSTRAINT "PageToConfigs_configId_fkey" FOREIGN KEY ("configId") REFERENCES public."PageConfigs"(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3237 (class 2606 OID 17285)
-- Name: PageToConfigs PageToConfigs_pageId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: cms
--

ALTER TABLE ONLY public."PageToConfigs"
    ADD CONSTRAINT "PageToConfigs_pageId_fkey" FOREIGN KEY ("pageId") REFERENCES public."Pages"(id) ON UPDATE CASCADE ON DELETE CASCADE;


-- Completed on 2022-02-27 11:10:02 UTC

--
-- PostgreSQL database dump complete
--

INSERT INTO "public"."Auths"(
	email, fullname, fname, lname, password, active)
	VALUES ('admin@localhost.local', 'Administrator', 'Admin', 'Boss', MD5('1qaz'), 1);

INSERT INTO public."Settings"("isDefault", data)
	VALUES (1, '{"websiteName": "Do Si Do", "websiteDomain": "www.dosidoweb.com", "websiteOwner": "Do Si Do", "websiteAdminEmail": "admin@dosidoweb.com", "applicationVersion": "1.0.1"}');

INSERT INTO "public"."DashboardBoxes" (id, title, module, "fontSize", "fontFamily", "textColor", "borderWidth", "borderColor", "borderRadius", "bgColor", height, width, "moduleOptions", x, y, scrollbars) VALUES (8, 'New Box', 'RAM Module', NULL, NULL, NULL, 1, '#959595', 10, NULL, 14, 1, '{"data":""}', 11, 28, 0);
INSERT INTO "public"."DashboardBoxes" (id, title, module, "fontSize", "fontFamily", "textColor", "borderWidth", "borderColor", "borderRadius", "bgColor", height, width, "moduleOptions", x, y, scrollbars) VALUES (9, 'New Box', 'NET Module', NULL, NULL, NULL, 1, '#818181', 10, NULL, 14, 1, '{"data":""}', 11, 42, 0);
INSERT INTO "public"."DashboardBoxes" (id, title, module, "fontSize", "fontFamily", "textColor", "borderWidth", "borderColor", "borderRadius", "bgColor", height, width, "moduleOptions", x, y, scrollbars) VALUES (3, '123', 'Admin Activity Module', NULL, NULL, '#3b3b3b', 1, '#959595', 10, '#b1b1b1', 56, 11, '{"data":""}', 0, 0, 0);
INSERT INTO "public"."DashboardBoxes" (id, title, module, "fontSize", "fontFamily", "textColor", "borderWidth", "borderColor", "borderRadius", "bgColor", height, width, "moduleOptions", x, y, scrollbars) VALUES (7, 'New Box', 'CPU Module', NULL, NULL, NULL, 1, '#7e7e7e', 10, NULL, 14, 1, '{"data":""}', 11, 14, 0);
INSERT INTO "public"."DashboardBoxes" (id, title, module, "fontSize", "fontFamily", "textColor", "borderWidth", "borderColor", "borderRadius", "bgColor", height, width, "moduleOptions", x, y, scrollbars) VALUES (6, 'New Box', 'Clock Module', NULL, NULL, NULL, 1, '#7a7a7a', 10, NULL, 14, 1, '{"data":""}', 11, 0, 0);

-- Main themes: dark and day

INSERT INTO "public"."AdminThemes" VALUES (1, 'Dark', 1, '{"common":{"black":"rgba(230, 225, 225, 1)","white":"rgba(161, 161, 161, 1)"},"type":"light","primary":{"light":"rgba(146, 146, 146, 1)","main":"rgba(110, 110, 110, 1)","dark":"rgba(185, 185, 185, 1)","contrastText":"rgba(53, 53, 53, 1)"},"secondary":{"light":"rgba(202, 201, 202, 1)","main":"rgba(136, 136, 136, 1)","dark":"rgba(24, 24, 24, 1)","contrastText":"rgba(207, 205, 205, 1)"},"error":{"light":"rgba(194, 122, 122, 1)","main":"rgba(136, 102, 99, 1)","dark":"rgba(122, 10, 10, 1)","contrastText":"rgba(189, 156, 156, 1)"},"warning":{"light":"#ffb74d","main":"#ff9800","dark":"#f57c00","contrastText":"rgba(0, 0, 0, 0.87)"},"info":{"light":"#64b5f6","main":"#2196f3","dark":"#1976d2","contrastText":"#fff"},"success":{"light":"#81c784","main":"#4caf50","dark":"#388e3c","contrastText":"rgba(0, 0, 0, 0.87)"},"grey":{"50":"#fafafa","100":"#f5f5f5","200":"#eeeeee","300":"#e0e0e0","400":"#bdbdbd","500":"#9e9e9e","600":"#757575","700":"#616161","800":"#424242","900":"#212121","A100":"#d5d5d5","A200":"#aaaaaa","A400":"#303030","A700":"#616161"},"contrastThreshold":3,"tonalOffset":0.2,"text":{"primary":"rgba(184, 180, 180, 0.87)","secondary":"rgba(0, 0, 0, 0.54)","disabled":"rgba(0, 0, 0, 0.38)","hint":"rgba(0, 0, 0, 0.38)"},"divider":"rgba(0, 0, 0, 0.12)","background":{"paper":"rgba(131, 131, 131, 1)","default":"rgba(63, 61, 61, 1)"},"action":{"active":"rgba(0, 0, 0, 0.54)","hover":"rgba(0, 0, 0, 0.04)","hoverOpacity":0.04,"selected":"rgba(0, 0, 0, 0.08)","selectedOpacity":0.08,"disabled":"rgba(0, 0, 0, 0.26)","disabledBackground":"rgba(0, 0, 0, 0.12)","disabledOpacity":0.38,"focus":"rgba(0, 0, 0, 0.12)","focusOpacity":0.12,"activatedOpacity":0.12}}', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAVwAAAGQCAYAAADiPNjjAAAgAElEQVR4Xu2dB3Rd1Zm2P/XebMnqVrNkyZZly93GxpieDBBKIECGAIGQ8mf+mVkrMytTMjNrTS8Jk0xCmIQktNBCCaH8QCjGNm64yZIsWb1ZklVt9a5/vR/eN1fG1r1CV0dX9757LS9f3bvP2Wc/e+/nfOc7R7o+k5OTk8JCAiRAAiQw5wR8KNw5Z8wGSIAESEAJULicCCRAAiRgEQEK1yLQbIYESIAEKFzOARIgARKwiACFaxFoNkMCJEACFC7nAAmQAAlYRIDCtQg0myEBEiABCpdzgARIgAQsIkDhWgSazZAACZAAhcs5QAIkQAIWEaBwLQLNZkiABEiAwuUcIAESIAGLCFC4FoFmMyRAAiRA4XIOkAAJkIBFBChci0CzGRIgARKgcDkHSIAESMAiAhSuRaDZDAmQAAlQuJwDJEACJGARAQrXItBshgRIgAQoXM4BEiABErCIAIVrEWg2QwIkQAIULucACZAACVhEgMK1CDSbIQESIAEKl3OABEiABCwiQOFaBJrNkAAJkACFyzlAAiRAAhYRoHAtAs1mSIAESIDC5RwgARIgAYsIULgWgWYzJEACJEDhcg6QAAmQgEUEKFyLQLMZEiABEqBwOQdIgARIwCICFK5FoNkMCZAACVC4nAMkQAIkYBEBCtci0GyGBEiABChczgESIAESsIgAhWsRaDZDAiRAAhQu5wAJkAAJWESAwrUINJshARIgAQqXc4AESIAELCJA4VoEms2QAAmQAIXLOUACJEACFhGgcC0CzWZIgARIgMLlHCABEiABiwiocMfHxwX/WEiABEiABFxPwN/fX3x9fcWn7OTJyX/7t3+ThoYGmaB0XU+aeyQBEvBqApBtRkaG/O33vic+f/Gd70weOnjQq4Gw8yRAAiQw1wRuufVW8dmxffvkXDfE/ZMACZCAtxPIyMykcL19ErD/JEAC1hC4pHC3bd9uzRGwFRIgARLwQAJ4CGH/vn1TenZJ4b751lseiIBdIgESIAFrCAwODsptt9xC4VqDm62QAAl4MwEK15tHn30nARKwlACFayluNkYCJODNBChcbx599p0ESMBSAhSupbjZGAmQgDcToHC9efTZdxIgAUsJULiW4mZjJEAC3kyAwvXm0WffSYAELCVA4VqKm42RAAl4MwEK15tHn30nARKwlACFayluNkYCJODNBChcbx599p0ESMBSAm4t3ImJCf36CRYSIAES8AQClgn35MmTMjw8LAEBAZKSkiLR0dHT8nvsscfkrbfekh/+8IeSnJzsFOvR0VE5c+aM7n+60tvbKy0tLZKTk+PUfi9Vqa+vTyorK/VjfF1GYmKixMbGzmqf3JgESMBzCVgm3DvuuEPuvvtu6ezslDfffFN+8pOfSEJCwiXJPvjgg/LjH/9YgoKCxMfHx6kRaGtrk5///OfyN3/zN/JP//RPcvPNN0t+fv6ntkWd3/zmN/LOO+84td9LVTp8+LD87d/+rXz9619X0b/++uvy7LPPSkRExKz2y41JgAQ8k4Blwr3nnnvkqaeeUoq7du2Sxx9/XH7xi19oyuD999+X4uJi2bZtm6xevVp+9atfqRBvueUWeeCBB+T06dMa7QYGBqpEFy1apPu68cYb9fULL7wgGzdulNDQUBXuFVdcIf/6r/8qubm58qd/+qeSmppqG73JyUm57777JDs7Wz73uc/JunXr9LOf/vSnkpaWJtXV1bJy5UrZuXOnfoFmVVWV/o/y5S9/WY/BFAj3Bz/4gTz99NPajz/7sz+Tv/qrv5L4+HjtzwcffKAR72233aYnDvQJEX5MTIzs2LHDM2cUe0UCJHBJAvMiXKQWPv/5z8srr7yiUsL/3/zmNzV9gH9jY2PyF3/xF/If//EfGgV/5zvfkS9+8YuaBjh48KD8y7/8i9x5553yn//5n/qtl4iG77//fpUohPsnf/InKj4IGeKE7Ezp7+/Xz7761a/KP//zP8vzzz+vskQ9yPzqq69WSUOkAwMD8td//dfyox/9SD788EPp6OiQv//7v58i3H/8x3+U733ve3pSwEngiSeeEKQacMwQ8O7du6Wnp0e3u/XWW/VkcNNNN0l6ejqnJQmQgJcRmBfhgjHEhogPl+RIASASRKSICBRRLSSKPC7KiRMn5Gc/+5k0NzdLcHCwPPnkk9MKF/uDsO+66y5Zu3btlCFFmgIR77XXXiubNm2S1157TSNbCBdpjhUrVmiqAemJZcuWafQN6UK2OElAvCEhIbpPRLgQKQTd1dWl8oZww8PD9cSASL2xsVEj7xdffFH7hKiehQRIwDsJzItwEanish6R7be//W2N9kyedsuWLSpjI1x8B9A3vvEN+e53vytxcXEqN0Sx00W4lxIuoluIFZfz2BfSFGgfkae9cPft2yelpaWyatUqjcAREZ89e1auueYaee+99yQyMtImXPuUAgQLeSclJcnf/d3fyfe//32NfBGpv/TSS/K1r33NdhLxzunGXpOAdxOwVLiPPvqojIyMaLSKy3hEoci1FhQUqARbW1tVVogIjXBxWf+tb31LHn74Yc2vQmK//vWvNYWAf9gWQoaITUoBwsW/6667TrZu3apPEKAcOnRII2qkLSB4PNWA14ikIVxIEjldRLRILyBSRdSNFEZJSYn8+7//u/z2t7+1nRwQ4SKtge2RBvmv//ovvTGIaBfvYd9vvPGGRrcvv/wyhevda429JwGxTLg33HCDNhYVFSW33367/oMIkd+E0I4fP66yQz4UaQP7lALkhfTDVVddpXlcyBcChDwhZ0gZ8rYXLiJU5FERXSJSRcFriB2pBFNwMw+ifeihhzT9gMfXCgsL5R/+4R/k6NGjKtzu7m49USCXi0e/TIFwcZy4CQY54yYcnljA88OQM/K3EDlOFI888oieOEyahHOPBEjA+whYJlx3R2ufUjDHeuDAAVtKwd2Pn8dHAiTg/gQo3PNjhKcWEDFnZmbaRg0365CGQBTLQgIkQAKzJUDhzpYgtycBEiABJwlQuE6CYjUSIAESmC0BCne2BLk9CZAACThJgMJ1EhSrkQAJkMBsCVC4syXI7UmABEjASQIUrpOgWI0ESIAEZkuAwp0tQW5PAiRAAk4SoHCdBMVqJEACJDBbAhTubAlyexIgARJwkgCF6yQoViMBEiCB2RKgcGdLkNuTAAmQgJMEKFwnQbEaCZAACcyWAIU7W4LcngRIgAScJEDhOgmK1UiABEhgtgRmJNzZNsbtSYAESIAEphLIyMwUnx3bt08SDAmQAAmQwNwSoHDnli/3TgIkQAI2AhQuJwMJkAAJWESAwrUINJshARIggUsKd3VhIemQAAmQAAl8RgL4Ru/ioqIpW1O4nxEmNyMBEiCB6QhQuJwfJEACJGARAQrXItBshgRIgAQoXM4BEiABErCIAIVrEWg2QwIkQAIULucACZAACVhEgMK1CDSbIQESIAEKl3OABEiABCwiQOFaBJrNkAAJkACFyzlAAiRAAhYRoHAtAs1mSIAESIDC5RwgARIgAYsIULgWgWYzJEACJEDhcg6QAAmQgEUELBNuUVGR+Pj4aLcCAgIkNTVVwsPDp3SztbVVgoODJTo62qLui5w8eVJiYmIkMTFxVm2WlpbK2NiY9jEwMFDS09O1LywkQAIkYAhYJlwIacWKFdpuf3+/VFZWSkFBgfj5+dlGY3Lyk69RM2K2YphKSkq0vZUrV86qOfQvJydH/P39paOjQzo7OyU3N3dW++TGJEACnkXAUuEaqSESRMS7evVqKSsr00hw0aJFMjAwoK8jIyNtkSfkjIjR19dXxsfHJSgoSNLS0mxSw89DQ0OSnZ0t+Ariqqoq3T4lJUXq6upUgiMjI9LQ0CDLli37VESN/XZ3d+v2eH327Fmti+Pp6+uT+Ph4jYCPHj0qixcvFgDD/rBf+xMDhLt8+XLdR1NTkx5rRkaGtLS06H4Q1WPbzMxMqa+vl56eHttx2p90PGt6sTckQAL2BCwTbnFxsUoQpaurSxDNZmVlqViNiBsbG23ChSwhMIgLUSjkjIL6iJQhV3yG/UBg2DeiS0SWEDLeR5t5eXmCVAXSFxCnfWh/+PBhyc/PVyGOjo5KcnKyChfHBzGiDbS9fv16OXHihKxatUqFCqkvXbpUTwSm2KcU0DaEHBISoicRFBwrjhN9hdCx7WzTGJzKJEACC4uApcKF0BAVhoaGqnDw2ggU2OyFCykh6kSBzIyUEREbiZ47d06lhYgyISFB9wlhGrEbsWG/ELa9ICFZ7KuwsFAjZBwHxIrIE/tADhaR+JEjR2TdunX6OeQM4ULgkGlUVNQU4ZqUQm9vr0bXEDTahmxjY2NVtDhZ4H9E8oieWUiABLyHgGXCtZemPd7PKlxEnohkIyIiVIYXEy5EWl5erpfzF+ZoIWlEsPjMRN1IOQCIiXCxPaLki0W4uOmHdIZ9hIuIHFG2yVGblInJXeOYTYRL4XrPImNPScD+ytqS7zRztXAhTESSiDRNGgESs49wTQoCcoSYTcElP+SHCNQUSBZRL/K/1dXVGjkjgkbedsmSJYL0A6JUROVoFxJFtGsvXDxdgc+xHV5jH4h0ka5AwfuQcHNzMyNcrkES8EIClkW4kI6JJu0527+PS28IC//wGtEiin0d8xrSxCU/CupDfvgfHbK/CVVRUaH51AvLxY4H+4N0IW2kP1DMMSOHa546wP4vvNGF/ZmnLHAs5tjxHj4z/cJ2OEYU3izzwhXHLns1AcuEazVldAyPniFincnNKcjW5HDtjxnCNTlcq/vC9kiABDyDgMcK1zOGh70gARLwJAIUrieNJvtCAiTg1gQoXLceHh4cCZCAJxGgcD1pNNkXEiABtyZA4br18PDgSIAEPIkAhetJo8m+kAAJuDUBCteth4cHRwIk4EkEKFxPGk32hQRIwK0JULhuPTw8OBIgAU8iQOF60miyLyRAAm5NgMJ16+HhwZEACXgSAQrXk0aTfSEBEnBrAhSuWw8PD44ESMCTCFC4njSa7AsJkIBbE5iRcJPO/41Yt+4RD44ESIAE3JQA/j52S3PzlKPLyMwUnx3bt3/yneUsJEACJEACc0aAwp0ztNwxCZAACUwlQOFyRpAACZCARQQoXItAsxkSIAESuKRwN23eTDokQAIkQAKfkQC+HPfwxx9P2fqSwv3cH/3RZ2yGm5EACZAACeCbwX//9tsULqcCCZAACcw1AQp3rglz/yRAAiRwngCFy6lAAiRAAhYRoHAtAs1mSIAESIDC5RwgARIgAYsIULgWgWYzJEACJEDhcg6QAAmQgEUEKFyLQLMZEiABEqBwOQdIgARIwCICFK5FoNkMCZAACVC4nAMkQAIkYBEBCtci0GyGBEiABChczgESIAESsIiAZcINDg6W1NRUCQwIkNYzZ6Szs9OSLqalpUl9fb3L2lqamir9/f3S2dU1q30mJyXJ4sWLdR/YX0NDg4yOjc1qn9yYBEjAvQlYJtyN69fL6eZmGRwakqzMTKmpqZm1tJxBW7h6tRwrKnKmqlN1Nm3cKIB25OhRp+pfqlJebq70DwzIuXPnZElcnCyKiZFDhw8LvmSOhQRIwDMJWCbcDevXy8eHDyvFqMhICQ8PVwHHxMTIqpUrZXBwUI6fOCGjo6P6ef7KlYI/1gtZDg8PS0BAgKwtLJSgwEApLi2V7u5uQZSIyDk+Pl4lePjIEcHXEGP7wjVrpLe3V3x8fOTweTnmLl+u27S0tsrJsjI9FtQLDgqS0rIyWZaVJUePHdP3N23Y8CkBRkZGSmJiou4f9dBmWGioLM/JEfHxkYjwcD0GiLRg1So97sSEBGltbZVTlZVTZArhtrW3a6SPfaxft0727tsnvr6+2vfoqCipb2iQmtpaiYuLk/SlSyU0NFSOHDsmfX19njkb2SsS8HAClgkXsgsLC1P5nGlrU1khvQAxlZ06pQKOXbxYKquqZP3atVJcUiJ+/v6Ss2yZyg2RZfmpUzI8MqLbHC8qUlmnJCVJSWmpStff318qKisFcq+oqJCJyUmV+b4DBwSyhBDbOzo0woaMm06flq1btkhxcbFKcl1hoZSePCnjExMqX7y2L5Ai0hNh4eEyMDAgbW1t2ids9/GRIxIYGCgF+fmy/+BB/R/7RwSbnZ0tp0+flu6zZ227g3DDw8JUyhBpTV2d7m/xokXi6+cnPT09kpOdLdXV1RIeESFpS5fq8QwNDmq/WEiABBYeAcuECzSQHnKgEM2JkhKJjo7Wy+nm89/Tnp6WppEm6pSVlyvNoKAgjWIh2b179wpUg3oQJASH6LS6pkZiY2NlaUqKbrdixQrbJb9JKSBCzszMlNDg4E/E39YmVVVVsnrVKikqLta2MtLTNSJG3a7ubmlvb7eNKNq5bOtWjUJxTCvz8uTAoUMqS0gdr31E5PLt2+Xo8eMq9fLychkaHtZoFflaHKcpEC6kevbcOVm0aJEkJyZqRI2+YtsAf389TvDAiSQuNvZTJ4CFN914xCTg3QQsES7EERoSotElCi7rIZD2zk6JiY6W5pYWfR8phLHRUY3mTp4XLt7HJfzqggLZvXevTYyIUIOCgz8lXAgqH8I9nxowws1etkxGR0akvrFR9+8fEPAp4SJdgRRDRESE7N6zR6NpU3C8SGngGFH8/Pw0ckYKwyZcHx+5fNs2bRsRshEuInFIt7aubopwTUoBb+7csUP3h5NCY0ODnlBwzB2dnRSud69R9t6DCFgiXERouOyua2iQoaEhyUhL08gOOdw1BQVSVVOj0SGiRaQbcIMNOU9fHx9JTk6WE8XFmuNsaGyUkeFhWZGXp5fwiBovjHARXa5ds0blhktvXNrv+egjjV4hUuwD6Y2uri5NP9hHuBhXiB3tXnijbc3q1ZpPHR4a0uFfunSpPlWAKBjHiygZwkY7iHZRHykE5GiR40U6BCcJ+wgXuVjUwQ2z1JQUOXDwoGRlZWlKoxcpBWxXXq4pBka4HrTq2BWvJWCJcEEXUS5SAQGBgdLe1qay1eg1KkrfR+QIoSE3ipRDZkaGiqeyslJGRkf1Mh/5XOR1a2trpbevT3O+SCsgQsZ+lsTGSmV1td6EQt50cGBA91FVXa03o3Cpjs/aOjpUqsixZmVkSHVtrW0CQJiIxO1vTOGEkZuTozfaTP7Uz9dXo1G0vSo/X2/iIR2A3DGexIBwz549q3nmrs5OaWhqmnLTDGkTpFNQ8FgYjmFkZET7g8gWqQ3IGDlb9AFRPm6isZAACSxcApYJdyEgSoiPFzy3e+jjj51+PAsnEpNSsO8jhGtSCguh7zxGEiCBuSdA4doxxpMOiGwRcTpbEP3iyQKkQuwLom9EqCbn6+z+WI8ESMBzCVC4nju27BkJkICbEaBw3WxAeDgkQAKeS4DC9dyxZc9IgATcjACF62YDwsMhARLwXAIUrueOLXtGAiTgZgQoXDcbEB4OCZCA5xKgcD13bNkzEiABNyNA4brZgPBwSIAEPJcAheu5Y8uekQAJuBkBCtfNBoSHQwIk4LkEKFzPHVv2jARIwM0IULhuNiA8HBIgAc8lQOF67tiyZyRAAm5GgMJ1swHh4ZAACXgugRkJ13MxsGckQAIkMD8EMjIzxWfH9u38atj54c9WSYAEvIgAhetFg82ukgAJzC8BCnd++bN1EiABLyJA4XrRYLOrJEAC80uAwp1f/mydBEjAiwhQuF402OwqCZDA/BKwXLgBAQESHRMjsbGx4h8QIB3t7dLV1SXDw8Mik7N/WCIwKEjwjbxp6ekSERExhW5vT4/U1dVJ25kzMjIy8pnIB/r5SWx4mKTHREtUSPCUffSPjEh991lp7emT4bGxz7R/bkQCJOC5BCwVbmJSksTGxYmvr+8UopOTk9LX2yt1tbUyMTHxmWmjM8uyswVfZz5dwQPJFadOSX1d3YzaSo6KlLz4OAnw85t2u/GJCanp7Jaqjs4Z7Z+VSYAEPJuAZcKFbJfEx09L89y5c1JfWysQ8EwLOpKblzejzU6WljotXci2IClhRvuv7OiU6vZOmXlvZtQMK5MACSwQApYINzg4WHKWLxcfu8gWUi0qKpKcnBwJDQ214Trd1KRphpkURLQ7r7rKFtni57SlS2ViclJqa2slKChI1hUWqsiPnzghg4ODuvvR0VF5/733ZGJ8fNrmfERkZ06WBNlFtmhjVUGhVJwq0/REdvZy8fXzk9qaKunv79P9jU9Myt7aOhkYGZ1Jd1iXBEjAQwlYIlxEtohw7cuZM2ekpaXlU8LtOXdOamtqZoQ7OTlZCtassW2TmJAgYWFhKtjqmhrJSE+X3r4+8fP11fzuieJiW92iY8ekubl52vaWhIfJutTkKXUSEpMlOTlFystKJTIySvr6esXP318SE5Ok7GSJrW75mXap7eqeUX9YmQRIwDMJWCLcvBUrBDezTBkfH9ebV4gS4+LipkS4yK+W2gnRGexbtm7VG3H2JSE+XqUL4a7IzZVTlZUSHBQkeXl5cvjIEVvV7u5uObBv37TNQLaQrimhoWGSmJwi4WFhUlVZYYtoExOTNX3Q2nLaVrdnaEg+qm1wphusQwIk4OEELBEuok8fH1yYf1KqqqokOjpaenp69GmFyMjIKZgRdc6kXHPttfrEw6WEm5ebK5VVVZpayFu+XA4fPWqrirTCu++8M21zO7LSJTQw0FYnKytbTjc3SU5OnqYQent7JCIiUnPU1VWVU/Y1NjEhvz9VNZPusC4JkICHErBEuCmpqbI4NlYR4jK/s7NTEOXicbDw8HBJTU214e3v65OqyqnScsQeTyZk5+RcUrjJSUnaDp6A8PPzk/JTp2x18bRCddX0QkyLiZYVCUts2yxeHKvpg+SkFGlubpLe3l7JyMyShvo6zQsPDX2SI0ap6+yWsraZ5aQd9ZefkwAJLEwClggXl/ZZ2dlTolzggnjxrGygXfSIZ2RbHORUL0SNm3I7du6c8rgZomakENra28Xfz0/S0tIEMXZdQ4MgbYECAe96//1PngGepvj7+sqV2ZmaA7YvKalLpb3tjISEhEp0zCL9aHxsTE6fbtR94+Syv65Rzg0NLczZwaMmARJwKQFLhIt0Qk5urkCM0xUICvlbRL8zLes3btR88EwK5H7k8GGnNslPjJfU6Cin6ppKvcPDmr/9LI+5zaghViYBElgQBCwRLkjgBll6ZqbeyLpYgWSRShg6/8jWTOlh/6vXrHH4rK/Zb2tLixSfOGGLdh21h+h2ZcISwfO4zpTOgQE51tQio5/h5OHM/lmHBEhg4RGwTLhAg98ww2NZYeHhEhISos/lQrADAwOaRvgska09cuw/MytLFi9eLBGRkYJfI7YvoyMj0tPbq6mM2urqGf9WGyJ1/EpvXHiYRAQFSaD/1N84ww2y3qFhgWxrOrv0OVwWEiABEjAELBUusZMACZCANxOgcL159Nl3EiABSwlQuJbiZmMkQALeTIDC9ebRZ99JgAQsJUDhWoqbjZEACXgzAQrXm0effScBErCUAIVrKW42RgIk4M0EKFxvHn32nQRIwFICFK6luNkYCZCANxOgcL159Nl3EiABSwlQuJbiZmMkQALeTIDC9ebRZ99JgAQsJUDhWoqbjZEACXgzAQrXm0effScBErCUAIVrKW42RgIk4M0EKFxvHn32nQRIwFICFK6luNkYCZCANxOgcL159Nl3EiABSwlQuJbiZmMkQALeTIDC9ebRZ99JgAQsJUDhWoqbjZEACXgzAQrXm0effScBErCUAIVrKW42RgIk4M0EKFxvHn32nQRIwFICFK6luNkYCZCANxOgcL159Nl3EiABSwlQuJbiZmMkQALeTIDC9ebRZ99JgAQsJUDhWoqbjZEACXgzgUsK9+prr/VmLuw7CZDAAiPw7jvvuP0RU7huP0Q8QBIgAWcIULjOUGIdEiABEnABAQrXBRC5CxIgARJwhgCF6wwl1iEBEiABFxCgcF0AkbsgARIgAWcIULjOUGIdEiABEnABAQrXBRC5CxIgARJwhgCF6wwl1iEBEiABFxCgcF0AkbsgARIgAWcIULjOUGIdEiABEnABAQrXBRC5CxIgARJwhgCF6wwl1iEBEiABFxCgcF0AkbsgARIgAWcIULjOUGIdEiABEnABAQrXBRC5CxIgARJwhgCF6wwl1iEBEiABFxCgcF0AkbsgARIgAWcIULjOUGIdEiABEnABAQrXBRC5CxIgARJwhgCF6wwlJ+oMDg7K0NCQ+Pn5ae2wsDDbayc2d1hlbGxM/P39HdZjhT8Q6OjokJGREX0jOjpaQkNDZ4xnYmJC+vr6JCIiQkZHRyUwMHDG++AGnyaA+dzd3S1xcXH6YWdnpyxatEh8fHycwrV//37ZtGmT+Pr6OlXfXSpRuC4aCQgXJSQkRBf58PCwLlKUycnJKRMJP6PYTy77OuZzUwc/9/f3S3h4uG1/F27vom541G7Ky8slNzfX1idwvHAsMAaQKhYu/kfBa/u6AwMDEhAQIM3NzZKWljZlTM32ZjuPAjiHncF8PnDggGzfvl1PYkePHpU1a9bomjBjZF7b/4wxwvvYdsOGDRrU2G9jxnIOD31Wu6ZwZ4XvDxvbCxdnb/yMKBcTC5EpBBwVFSVYvFjQqIOJhs9QFxMHERQk3dXVpdEYfg4ODtYJiOgZ+8N7RgzYBp+zXJyAvXDB7MSJE5KYmChnz56V5ORkHQtwrq+v15PZ+Pi47mjx4sXS3t6uY7NkyRL9HO8hYs7KypKTJ09KfHy89Pb2SnZ2tlRVVek4YPuMjAwOhxMEsC5KS0t1Laxdu1aOHz+uwq2oqJDIyEjp6emR9PR0qayslNjYWJ3/iIZramr0fdQHe0TGy5Yt0+3y8/NVxIh8zZWmE4diaRUK10W4IU1IFJEQ5IpIFz+jYPDxORY1JhrEC4maSBgLG3WwgGNiYvR/XAJjP9gHRIvLWmyP/1EX7bAFGfgAACAASURBVODM7q4Ty0VYZ7WbY8eO2dIwiHTBDlJsaWmRvLw8gZDBGeOBxY+FCt4QLNhCrjjBQahY3Ihwsfix2DMzM1XAK1asUClgP/gXFBQ0q2P2lo2xDqqrqzWNAOm2trbq1Qjeg1gxNpdddpmuBZws29raZOnSpbomcPIzKYUzZ87oGsCY4eoDaYrly5e7LUYK10VDA6FiYiBqxWucpbHATRRrUgA4c2OBm4IJApEacWKhnzt3ziZcLHgjWpNSwHuYsIiqGOFeegDtI1wsVES469atU0FiUUKcECQW+sGDB2Xjxo0q3IaGhosK9/Tp0yoDRFOIxlDMSRXjgeirsLDQRTPKs3djhFtQUCBFRUV6Ylu1apWKF+JEQIIrEQgVYwXmuCq5ULg4eWINIHipq6tT/u68JihcF81r+5QCRIsIFGduE+3ikgiXrzhj26cGUAdRFyYJJiFSChcTLkRtxIvo2aQZIHYWxykFiLG4uFjHBSdGLHSc7LCgIVwsbnvRYiHbR7g5OTkqBly+4jLWjCMubyF2jCHSDwkJCRwOJwjYCxdzu6SkRDZv3qwnLaR6MK/Bs6yszHazMzU11SbcPXv2aHSMgqsMrIcjR45oXtedC4XrotExd8MR0WLwIWAI1qQa8D6iKSxMk8fF54ho8bORLoSAyWikbN4322Af+BwFdZy9q+uibnI3JOCWBBAhNzY2aqrHnQuF686jw2MjARJwSACyPXTokKYTPsujfw4bcGEFCteFMLkrEiABEpiOAIXL+UECJEACFhGgcC0CzWZIgARIgMLlHCABEiABiwhQuBaBZjMkQAIkQOFyDpAACZCARQQWtHAtYsRmSIAESMBrCGRkZorPju3bP/kTWywkQAIkQAJzRoDCnTO03DEJkAAJTCVA4XJGkAAJkIBFBChci0CzGRIgARKgcDkHSIAESMAiAhSuRaDZDAmQAAlQuJwDJEACJGARAQrXItBshgRIgAQoXM4BEiABErCIAIVrEWg2QwIkQAIULucACZAACVhEgMK1CDSbIQESIAEKl3OABEiABCwiQOFaBJrNkAAJkACFyzlAAiRAAhYRoHAtAs1mSIAESIDC5RwgARIgAYsIULgWgWYzJEACJEDhcg6QAAmQgEUEKFyLQLMZEiABEpi1cAvXrBHx8ZGBgQGpq62V4ZERiYiIkGXLltnoDvT3S2NTkyxfvtz2XtuZM3K6uVni4uK0fk1NjX4WGxsr0VFRUlVdLf7+/rJyxQopKy+XJUuWyMjwsLS1t0tISIjk5uZOGb3Ozk5paGhw6YjiWHz9/GRyclL6+vpkcGBAQkJD9XhRRkZGpOfcOf180eLF0tvbKxPj4/q6u6tLRkdHtV5EZKQEBgZKV2en1vX19dU6Z7u7ZWxsTOtERUdLUFCQfg5e/f39ErNokQwNDsrg4KD4+fnpzx3t7S7tIxgnJCSIn7+/dHV1SW9Pj0RGRek4mHLu3Dnp7OiQsLAwiY2Lk/HxcTnT2mrrX3RMjMRER0v/wIC0t7VpH5JTUvS40WeUpUuX6viAXdySJVoH7DBupqD/ScnJ0lBfr234+PhISmqqBAQEyMTEhPYdzPFeY0ODth8VFSVBwcGC+eTKMjw8LPiiP18fH20fx4JjRpsYS5TRsTEdb4wNOJqCOqhv3sOx47ixTuz3hzawb8wHU4aGhmyv8T7autixuLKvl9oX1l7pyZO2j3EsWNcnT56UnJwc6e7ulvb2du1/Xl6elJ86JUvi4pQR3sc6TkpK0vULdiwisxbugw88IEeOHJH4+HiJCA+XV159VRLi4+Wqq66SY8eOyQQEMjCgMrr6qqukuKREuXd0dEhra6vceOONugifffZZHZSVK1dKRnq6vP7GGyrWL999t7zwwguyqqBAZXCiuFiCg4N14DGgqampuk8IDgJ3ZVmRn68LGTKCgCrKy1WM0dHRAglBmufOnlX55K1YIY2NjTI2Oio5ubnS1NiokkLJzskR/4AAOVVWpuKAWFCnuanJJhwMBBYWRAOpVZ46pftHX3Eii09IUB547cpSsHq1igGCh+z27t6tiyQtI8PWFsYO/d2+fbsupOCQEJmcmJBjR49KTEyMrFm7VlqamyUhMVFlWVNdLVu3bRM/X1/Zu2ePjuuOnTvlww8+UBGnp6dLS0uLpC5dKvV1dbZ28Fn+qlVyYP9+5erj66ttYp6goP5He/bI5q1blSXev+LKK6W8rEzbd2Xp6enRcYJUZXJSwsPDdezACfMVgQUCACNEjJMRMXihz5GRkZ+IeXRUhlA3IEDFi3rY99mzZ3VfEJYp4Ix9oUDaqGvew7H4iOiJz4qCtffrZ56xNYVjvfGGG+SZZ5+Vm2++WSLCwuSZ557T47/zS1+S37z0khTk5+uJtqKyUu6+807ZtWuX1NTVWXG4C6KNWQv3/vvvl2eeeUZGR0bk+uuvl2PHj+tC27Ztm/zmxRdVICiIZDdv2iSvvf66DQwm1u1f/KIu4pLSUmlqanJKuGYHKSkpsrawUH732mtzAhvCPXn+BLE0LU0QfRhhnm5qUgEmpaRITVXVFOFCDFhYkGNgUJBkZWVpdGOEi20QGRmZ4uAxEGfOnNHoFuLD521tbSrmqooKWZaTo1Fdf1+fS/sKYR3cv18XyZL4eI26ExMTJSEpSd83JWvZMpXEydJSFQFEXXzihMoP0gQP9GfDxo2yZ/duFW5oaKge86ny8inCxdUKZI2rhfXr12t9lLXr1mmUjaivsqLCJtwjhw+r6DZt3qwnNZx4V61eLWWlpbJx0yZ57913bVcKroID4Rphom2ID2Ixwu3r7xd/Pz/tM+Y4BIsTF16DJf6HoBClQrj4Bx54H/MI0ryUcBG12xcI17wHmWPe2UfUrurzhftxJNzIiAgpKSnRtXuhcLHex8bHZc+ePbpmWD4h4DLhIjpbv26dQsal3zXXXCNliOgmJ6W8vFwX63XXXiuVVVXaMD4LDwuTFYgMm5okJztbo1r87CjCtVK4kCQirbT0dI1YMdGxyFpbWjQCxeRHVGcf4SLSw0KrranRaBHbh0dEqHAhXqRDqiorJT0jQ//HhMRA4MQzPDSkkRwutRHlQYJYbFiwro5uwRFRZc7y5Sp7RNyQQFpammRkZUnz6dOKuqqqSlavXq2foU+mIPLffvnlUnTsmF5eophIFsLt6ujQE9L+jz6SjZs32yJcI1z7+hDa+o0bVfJbLrtM9u3dq5f0iHCLjh/XExhkDsmjLYgeY4Fo2hynKxe1vXAhUBTMYSNciBNXbuayHycJFKRVIGKMKY4P72uEOzRke435g/cvJVy0gwLBo569cNE+9mvquLLPMxVuSXGxFBYWyv976y259ZZbbBEurjpxsnniyScp2wugulS4mzdv1ggMC2Lnzp16dsPERN4V0cIVO3bIoY8/1kPAAsfPzS0tOnG3b9smzz//vIonMyNDI+FLpRSsFC6iORQswMb6er3cT0xKsuViEb3h0tJeuIhQsTCw6BbHxqqcIWEIF5emKchn1tVpLhOLCXlO9DssPFyjR+SLa6urtV2IKHfFChUzol9XF+SoccmMCBZR/J4PP9QINzUtTS/VUXCiKVizRiNLCA4Fix5R3fYdO+REUZEtV2svXPDC/nGyQUrGpBTshYsIe9f770tmZqayqq6qkvyCAo2kcdKBcHGVAPnU1dV9ctI6f6LAMe/etcvVSGzjbSJcCNdc3hvhou94DzIdGByU4KAgHStEoCYlgCAE4kEdnDA0RTE6qtwQ7V5KuCZlAJnjn7sKd//+/ZpPj4+L0yvYF158UVMKCJpwpYIAYv+BA8zf2s1QlwkXkwjpAUSpyOU6SilgUn3pjjuktLRUo2JEtfv271fJbtywQZ5/4QXND37hppvkueef1zOpyeFaKVwIFUIyqREIFznMttZWyV6+XOpra1Wu9sLFJETUhSgRJyDcSILAIAvIGpEhIp6gwEAJDQvT3DCiXUxQ6B11Kk6d0m5iwUFAqGN/Q8UVlkH0tH7DBjl08KD2D5fnkCy4X5hSwDHh39HDh/WYNm/ZIvv37dM0AE5GSAHgBJKZlaVRKiJcCBe5WryGbH7/9tsaURvhYn+Q/KEDB3R/kBXkhhw5cqSlJSWfRLhFRRIWGqp5bKQiUHADETdq9n30kStQfGofJsLFvO7t69P2IVhbSqGvT/sEhrZUU3CwnhRNtAvhmtyvSSnY54FnmlLQY+nt1X3a32ibEwAiev9kuhwuhIsbn6iHexRPPPWUChdjh5PjHbffLi+//LJ02N0YnatjXSj7nbVwH/ra1/RmFc7wSA0cPnxYkhITNZ+L6FXvRvf0SEVFxZQcLp5YyF+5Ul5+5RWtA+FmZ2fLrg8/lKuuvFIjKPyrr6/XvPDWrVslJTlZenp7le1bb70lycnJluVwzYBCuFhoyFli0eMmGqR7oXARkebm5Wm98YkJFQuEC0kjJwvBYZKiDmQKEZkcLtIXWFiIfOdSuOgTBIm0BZ6WgFAgVOTGkTNGPhcFKSKkTVYXFmr0hqgV/ULuFk8IrF6zRk8U6E/5yZMamRrhIueKiB83w97BmKWk6NMqGEeML05ofb29ctn27RpdgwtOQuvWr9cbbhAucri4CsI+UR/HY4VwzRMqAefTSPayNDfC9OmFiQkNFEZGR8UfTxacTwlAzji54p6GedIEKTacaBENQ7hgYK6iEPUimjXCRioqNCRE38N+9P7B+RtuVggGN8TNjejm5mZ9ksj+phmEizmLK1KkEJ98+mnbTTPc3Eakm71smbzx5psuz7Fb0f+5aGPWwp2Lg+I+SYAESMATCVC4njiq7BMJkIBbEqBw3XJYeFAkQAKeSIDC9cRRZZ9IgATckgCF65bDwoMiARLwRAIUrieOKvtEAiTglgQoXLccFh4UCZCAJxKgcD1xVNknEiABtyRA4brlsPCgSIAEPJEAheuJo8o+kQAJuCUBCtcth4UHRQIk4IkEKFxPHFX2iQRIwC0JULhuOSw8KBIgAU8kQOF64qiyTyRAAm5JgMJ1y2HhQZEACXgiAQrXE0eVfSIBEnBLAhSuWw4LD4oESMATCVC4njiq7BMJkIBbEqBw3XJYeFAkQAKeSIDC9cRRZZ9IgATckgCF65bDwoMiARLwRAIUrieOKvtEAiTglgQoXLccFh4UCZCAJxKgcD1xVNknEiABtyRA4brlsPCgSIAEPJEAheuJo8o+kQAJuCUBCtcth4UHRQIk4IkEZiTcyclJGRgYkPGJCY9g4evrK8FBQeLv7+90f0LDwiQ0NFR8fHyc3mYhVJyYmJC+3l4ZHh52+nAXx8ZKRESEx7FwGsD5ilgXvb290tnR4fSm2GZ0dFQmnd5i4VXEGvH38xOsM2fL0NCQjI6NCfjMd8FxBwUGSkBAgMsOxWnhYkFiMQYFBc0IoMuOdA52hEEdGh6WwIAA8fPzc9hCSGioTJ7n4A4TwuEBz6ACJldEZKT09vQIxtpRWbRokbIbHBhwi8Xh6Hjn8nOIJTw8XEJCQqStrc1hU5g74+PjOuc87cRt33n0c2xsTAMaZ/qJk1ZwcLBLBedwMKapgOMfGRnRcZpJUDZdm04LF+CwKGdytppNZ63cFlADAwMdNhkZFaVC8jTZmo7jTI6FAR6OCoTb1dXlqJpXfZ6ckiLNp087nB+evJYuHHCcvLFeHAU0qNPf368nLncqJtDEydQVZUbC9dQzsoncHQH1dOHiLI4xdiatQOF+erYkJiXJmdZWh1cIEK6nrqULqZho3lGEaNKVYWFhjpahpZ9DuEhzII3oikLhithSJY6AUrh/IEThUriO1gs+p3CnUqJwKVzbjGCE64xCLl2HEe6n2VC4FO6nZgVTCp8goXAp3NkRoHAd8ZuTCHfzpk16KXGup0eqq6r0MY/4+HjJSE+3HU9TU5Pe5V6WlWV7r6ysTLfJyMjQGzenT5/Wz3JycqSvr0+am5v1LmZ2draUlJRI/sqV0tjUJGfPnpWYmBhZnpMzpb/19fXS0trqiIHLUwrR0dGCJxpQ0I+z3d3KIzYuTnN3yAvhmIeHhvRmXVh4uHR3dQkipP6+Punp6bEJMG7JEulob9dHiFAiIyP1f1MHPGIWLdL3RkdGpLu7W3z9/CQqKkq3Q8HlP7bHXeDpylwIFzdZk5OTJSg4WLo6O/VGW3hEhL5nCm5EYmzBLCkpSfngZ/BBAU9wGOjvl5aWFv0c9fDgUEtzs9bBRK6rrRXkAHHzSuffuXOaUzUlIDBQ0tPTpb6uznZjcGlamj5dgKcG8FgXGKVnZEhTY6Pm7sAbqST87Ki4OsI1N2zEx0fnDZ6mQcGx4jPc5DR30vE/fjY3p/AzAgnML3OjG3MR22J/eFzLPO50YcChT++cZ4/2MC+wD72ZesG2jpjMRYQLP6AfDQ0NtuYLVq2S5pYWfWw1Pz9fioqKtP+YZ2CCebO6oEBOFBfrtqh/urnZ4VMlCyKHe+9XviKHDx+WzIwM6R8YkPc/+EBWrlwp2cuWyalTpxRSe0eHSjIvN1cqKyv1vYbGRhkcHJR7/viPpa+/X15++WWdUNdfd52COXrsmIrkumuvlRdfekluveUW+fjjj6W+oUGfB01JTpaExEQJCw2V6upqOXPmjHR1dzuaEy4XLhYxBhlShAwxCc60tMjyvDyVID7DM6zlJ0/qCSR2yRKpq6mR1YWFeiynysq033FxcZKUkiIVp07p41d4giBv5Up91KaivFz7FRUdrX3uaGuTqJgYmRgfV/GgXm11te4vNy9Pas6/tlq4K/PzVbbnzp5VkR3cv19PMKsKCqS8rEwPB33DCWjrZZd9wicgQMWJupBt4bp10tjQIEvi43U/pSUlsqawUNnu3rVLF9DlO3bI3j179KSWt2KFMsBiw4kMJ3IUMF+/YYMcP3bMJuLNW7eqaLEPHN+Bffskv6BAj6O2pkY2b9miixX7c1RcLVyMMwINnBBGRkdVkvp6ZETGxsclNCRE1xeeCDdCNM9Foz/YFvMLj3Ki4CkAzCFzYxSMzTw1J3IjdNTFM+ooOIFDPFib2B/ah6zx2lGZC+HuuPxy5bF//35b83fcfrscLyqSjo4O+eJtt+lnxSUlsn79ej1WCPhLd9whv3nxRUlMTJR1a9eqX7Cf6cqCEO5dd90lzz77rE4CSPGd3/9eUlNTJS42VnZ9+KGtf4hUE+LjZc/evbb3EhMS5Jprr5Wx0VF5+513pLOz0ynhmh3k5eVJdFSU7D9wwNFcsH3u6pQChIt9IrrCYGdmZUlVZaUKt6qiQqPNnNxcjc4gSCPcgjVrdGJDjpBQVna2LjJE6vgZEWDWsmU64ZsaGlTkEC5EUlNVpdFM5rJlKvLE5GSNiLBIENmddiJCm4sId8fOnVJ84oRGt4sWL9Z+IGJcsXKlfPDee7YxSEtLk0WxsXLsyBF9L3/VKjlZWiqFa9fqSRMnD7C8bPt22fX++ypc7A/zo+jYsSnCBW/I2tQ3Ui5YvVrFjpM2jgkFwoXAEWWDf8/5qHjDpk1y+NAh2bptm3z4wQe2K4zpJtVcCRcnHcwLnMAhRojYCBfv4VEqrDX7px/MkyaYa+ZRK0gUTDBPMHcgW8jY7Nf0DbLG55C3KZhzJuI3MsexOHq+dj6Ee9utt+qV4gsvvihr1qyZIty9H30kW7dskVd++1vbVaLHCBcduf7666WiokLPzAj1TZrg6NGjGoEUrlmjl/0Q7JGjR2X16tU6uRClDgwOaqTsTITrbsLFRG9H1BkVpVLEZSyEC3GgQIyQJCa9Ee6q1as1IoOEEZ3jMhlczrS1qahwWW0er/Hx9ZXmpibdN6K6+tpajQajFy1SqaNe9vLl+j9kj+0dlbkQLo4NUS4i09NNTdLe3i7xCQk6zkgroZwqL5fly5cL+gT5mYLFDCHi+MES5fIrrtCoFsIFY8yhgwcP6v5MhGuEi8WO+vv27lUhIVr9aO9e3ef+jz7SeYbXaH9ocFDljiswRLx4jd8qxIkNJzxnylwKF+3jZAF54riNcCHCwaEhCfD3V5Ga+YHUCOpCsnikCf3Ha6Rh/M7LGREu3r+YcHGFaVIYuELBPDTCBVdsAyE7ei5/voRbXFwswbgC6O9XJibCxUmprb1d3n77bWeGVFm7/WNhJsJFj2644QYpOn5co5q0pUu14yiQCHIxyOGWlJZqx1pbWzUixqUBhIvPcSZCCgELFSkFRK/XXHONvPTyy1NSCu4mXPTX5Noa6+s14oVwUSDZ1pYWlQgWhS3CXb1aqqqqND+JSyMsorCICI2UIczsnBzlgAmEvCxSDRAuokP9jZ6AAJUTcp0oSDXgt8cqz6dxHM2wuRAu9omxTV26VI//0IEDGqkjgsWlPQryujnLl2t/S4qL9T3IA0LdtHmz1NXVKS8URMyIOCFcXDJDLEnJyRIZESF7du/Wk48Rrqm/d/duZYETGNIYy7Kz9QSIX1KAcCEkHZPWVik+Pz9xckNEvOfDD536RRC0NZfCNTlpSA7zyggX7+PEBCkMj4woBxOhIsjBvEPf8BryMb81hfpgjH+XinDNw/7YBmOxkIT75NNPy+233aZ5Why3ES7GGKkppBMc3dPAmC4o4SLHdOutt8qzzz0nubm5DlMKixcvlquvvlrKz+cnV+TlycuvvCJr167Vxbh7zx6VMBLer73+ulsLF5EH8s74VWDzmzYQLtIFOJngxhEW/RThrlmjEkUEiMmOvC4WMSYJ9pOemWm7EYY0QnVlpeZDIRnUzcjKkq6ODttvgOGSG59D+M4UVwsX+8MlOS7NcYm6dt06jXJx4+XClAL6ACEj8kTUhHwuIlbUw35OFBVp6gT56I/27LEJFycYRK44wb37zjtThIscOJib+pAPpINLYeQfPz50SDZt2aISRuoGKRykIlBQZ+369QJZ42TmTJlL4Wo+t79foiIjVX4QbkhwsJ50MIcgXVu+d2RERWFOdtgWdTAGJqWAVBPmJU42M00pIO+J7SF3d00p/Pyxx/Qe0lVXXaUBnREu7v1kZWVp8Pfq737ncFgXhHAffOABvSRGfujY8eN6Aws3zZCoNjexcKMMnbHP4e684gqdFAcPHVIQWzZv1v8R8V65c6cuRJyRkWbA0wmIhjHguKRCeeONN1Ts7pTDNSOKKMHkcLFYENHhchXFPocL4UK2iMhw8ywtPV2Fi4gWfTV3yyFlLCgsMpPDhcQRHWMfKPMtXBwDnhhAdIs0CVIGx48eleiYGBUm8rooSDcg7YQbfTHR0foe+oyTE/LPq1atksDzf8MD6RKcyEyEC+HGxsaqHI1wEZkiF4v28DnaMTfVEP1Btlsuu0yj1/UbN9pyuHiNpyOQqnEn4WKckQqAYPHa/qYZTiIQIG6cYX4gTYDIzUTtYGnyvJAk/vAU1pHKNiREI148zeF3/g84IbAx88r+PV1ng4O2pyAwRx39ui7anquUAu4JnT13TufKnj179CrY3DRDDhfCxckFr3FT3f6mGfjhxtqxY8ek7HxwdynzLgjhOjxtuFkFV980c7PuOX04ro5wnW7YQyq6OsL1BCxzIVwruVC4c0Cbwv0EKoU7u8lF4X6aH4U7lcmc/OLD7Kat9VtTuBSuK2YdhUvhOppHFC7/loJtjjDCdbRcpv+cwqVwHc0gCpfCpXAdrRInP6dwKVxHU2VGwuUfIOcfIDcTCr9Wi1/SYPkDATwPjOeFHX1jhrf9PVzwcPREgzv/PVykHC3/A+R4nAbP/znz+9MLaRHiERGcSBz9gWT0CY9d4RcQ9A+AeFgxXxOj31nnRP/wmBoeJ3Kmroehumh39G9ixMU59UduIBdnJOQJ3Gby7Rb4+yqYV/hNOHcp+v1qExNOfSOMM8fsdISLnQEeBDXhBl/w5kznHNWBZMyvRDqqi8/1OcfwcH2+z7O+QlL0OU+cyc1vqTniYX7bzZmvJnK0r4X+OdhhXSDid/aXJHCi8pQvY51u/CBPR9Gt2V7/StnwsJ6M8Hq+i/kSTPPHf1xxPDMSrisa5D5IgARIwFsJULjeOvLsNwmQgOUEKFzLkbNBEiABbyVA4XrryLPfJEAClhOgcC1HzgZJgAS8lQCF660jz36TAAlYToDCtRw5GyQBEvBWAhSut448+00CJGA5AQrXcuRskARIwFsJULjeOvLsNwmQgOUEKFzLkbNBEiABbyVA4XrryLPfJEAClhOgcC1HzgZJgAS8lQCF660jz36TAAlYToDCtRw5GyQBEvBWAhSut448+00CJGA5AQrXcuRskARIwFsJULjeOvLsNwmQgOUEKFzLkbNBEiABbyUwI+Hiu4m+9tBDsn7DBo/gVVNdLf/zox9Jb2+v0/3Bd5qlpKZKUGCg09sshIrnenqksb7e4TfO2vcFXwuem5fnsi/YWwicLnaM+C64U2Vl0tLS4nQX8J1d+FJWT/l+wIt13BffGYjv//Nx/hsAN27aJF+6806JiopymuVcVWxoaJCnnnhCamtrXdaE08INCwuTv/zud/XbbVNSUlx2APO5IywQ9Oe/H37YqW9bDQ0LE0gGJx5XfW3yfPbfvu2+vj6VbX1trVPSxUlnaVqaytbTWMx0TPr7+/XLI1uam6W2psapzYdHRtziixKdOthZVIJsA52U7mXbtsmNN90k+NJGfHvvfBacEM+cOaMnxR8+/LC0t7e75HCcFm52drY8+NBD+s2u7nD2cUXvEdlCnr979VXZv2+fw10mJCRIaHi41sOZ25MKxhUsGurrZXRkxGHXVubnS0RkpH7FvKexcNj5CyrgG3uxQPHv0IEDDkWKE9vI6OhMm1mw9fHN2I6+uRdi/v7DD8vg4OAn344dFjav/cVYIgjBcR85ckRefOEFlxyP08JdtWqVfOcv/1IbfeONN1S8mDgLsehZNzBQdu7cKeHh4fLE44/L+++957Ar6RkZEhUdLefOndPLR3f4KmeHB+1Eyoh2VQAADidJREFUBUyqjIwMFWdFeblOekcFl36LY2OVQ2tr64KdC4766ehznHBSU1MlNjZWhgYHZdeuXTLpYF3gK9JHx8Yc7dpjPvf389MryekK1uSvnnhCZVtfXy9Hjx4VcJqvgij7iiuukIiICDmwf7/89JFHXHIon0m4zz///IJfYBjY6667TmJiYmYs3K6uLmlubnbJALjLTnJycvQkNFPhYnHg0subC1JsSUlJFO4lJsFMhVtZWSmHDx+e1ymFIOTaa6+V6Ojo+Rfuc889t+CjOwp36nxGyghn9ZkKt66uTtra2uZ1ccx34xTu9CMwU+FWVFToZfx8Fns/zHuES+F6XoRL4X725U3hUrjOzp7PlFJwJNzf//732v7ixYslPz9fL1UbGxulrKzMdlzLli3Tu9vFxcW299avX693J1EP0VZmZqZ+dvz4cb1RhzzjwMCAFBUVyebNm+XgwYOC/SB/higL9ezL8uXLJS0t7aIs5jLCxZ1Nk3+yv6lkbq6gbeRL8Rny4KiLn4eGhjRJb25CIUeMXDlYmEdrcDccxeTE9AbM+Ztcpi1sh3rgjoLjwfbT5dHmSrhoc93atZoLq6mpkZraWkmIj5e1a9faxgV54GPHj2t6p3DNGhkbHZXjRUXSc/5xvaWpqZKbmyudnZ36PnihHvqJn1Eu375d9n70kcTFxsq6des0j9p0+rQUl5TY2gkNDZXt27ZpPTxZgLJlyxaJiY5WRhWVlZqPxr4Offyx5uqTk5MlOSlJf75UmSvh2o+t/bxA//EZ5gkYmHmFn83NKTN3MAcwL8w8MPPSz99fcDMLxcwx0z+zrfkZ+8Q+wAjF/licEY2rI1z4AceANJgpBw4c0LWuOdcDB2Tbtm0SHByscw5rAZ/t27dPxxuc8Bo+udQTVwsqwn3kkUdk+/btUl1drYv8hhtukGPHjsmpU6cEN99QlixZoo9alJSUyMqVK/W99PR0hfToo4/qXcp7771XRfHb3/5W8IQAJNvd3S2vvvqqfOUrX5Gnn35aLrvsMsnKytJnafHcHMSOu4t5eXm6DaR/sTKXwoU4MWnRdww22oI0scixAMwiwQ07LBxMZPQbfcDENndosZCwGPCzWTTom/1dXOwfdbBfI2OcyNAW9omJidd4z+zjYjzmSrh/9PnPa9+R88Zk//Uzz8iimBi58YYb5O133tFDOXvunOaB77/3XikvL5eg4GBJTEiQx598UpYuXSo3f+ELmtPDMXZ0dMgbb74pt91yi96seuTRR1U43/z61+Vnjz0my7Ky5OqrrpJ9+/dLwapVcqatTdsB86zMTLn9i1+UV197zXbyv/+++6Sqqkr3sXnTJnnq17+W66+9VhoaG3Uf933lKyrtj6fJKc6VcMfGx2Xg/DhibDF+GFMcK+YNXpsbnEaImCuYHxArghOwNyde8wSAr5+fjAwP65zA/MCcwlw0Bfs22+I9ExhgXmN/mK+Y23jtTHG1cN955x3tE25qmfL444/Lhg0bJD4+Xp544gm5/PLL9WeIFetj48aN8stf/lKdgjQYgrM777zzks+QLyjhPvbYY/Lggw/qJH/qqafkxhtv1E5iUV1//fU2SCdPntSFePXVV9vegzBfe+01PQvddNNNCtAZ4ZodIGJGJGQ/GPMhXExSI1dMXkRXEB/+x2d4bSJXe+FioM1CwHZgaGSJRWQWjZEpFiIWIPaLhYLPsejMUyRYUGZxTrc45kq4f/Ltb8vvfvc7qW9o0BtLOKkgYsQ8+O8f/tB2SBs3bFCBvvTyy/re9dddJ79/910VJObOgYMHldc3HnpIfvg//2MT7unmZvnNiy9OEe7WLVtU1mD09a99TX7y05+qJG65+WZ9iB0S/91rr2k7EO6bb76pYr7pxht1jpaWlsp9994rzzz3nDxw//3yox//WHleqsy1cCMjI3UMjRgx5mZM8Z6ZU5gfmFuYQ+aqB09DhIWG6qFjbkCUWFt4jbmBOXpR4Q4OSrjdo1ngBwYmSMD8xWtnfqnBauHCOTi2+++/Xw4dOjRFuFdeeaU+SXLPPfcIuF6qLEjhojOvvPKKrFixQs+YSIRj0aHgDISIFGcgvIdJgPcAyEwCLDBcGixE4ZpHz0x6AYvfRJr4zEjY/MaRiXDNb+aAgZErOGAhmUVkHkfD+0a4kDLaws9YgKiDNrAw7SPkS02wuRIuLuVu+PznbemAUxUVsjwnR6PWk+dTTG+9/bZcuXOnHhpemwJOiHp379kjVdXV+vb/+eY3VaCIcNE/pKwgxptuuMEW4RrhggHqP/aLX4h/QIDce8898tgvf6lR6y8ff1xZQbjvv/++4Dftbr/tNpV8XX293HrLLXoVhvl49NixaQM5K4Qrk5OaYsFYmpQC5gzGXFNR/v76CwYmbdTX36+iBSNzwsZ8wm+24TfAMC8wT8D4YsLFXDX7QjvmSgoiA1ecOPF6uqsmA20+hIv0ZE9Pjz5lgHVjIlz0KTExUb7whS9Me7JYsMJ94YUXZNOmTYJHqZBPwWsURK54/ANpBuTcMHAAgbNTYWGhygnRyJe//OUFKVyTSsDAYcLif/QJ/2PCQqj4p89k2qUUsAhMisDkd41w7VMSRqz4HwsO+zWLyOTxsB/sH/t0VOZCuBqtBwcLfquqoKBArrziCpVjVGSkINWAyBQFudadV1yhYnj9jTf0PUQfEME9f/zH8vHHH6ucsb9vf+tb8j8/+YkKt72jQ3Oua9as0dztoz/7maYUjHCxn//77W/LT//3fyV/5Uqde7t379bPDx46JCeKi1W4iOQwRmXl5bb2kX74wk036T4hremKFcI1krtQuHgfXMAYaQJIEGNuf/lvUhEQLl5DOpgb+H+6CBdMUPx8fT8lXIyNMydybD8fwv3mN7+pLkEwh/lvhIsAAFfRd999t94z8KgIF4OCPOtDDz2kN7ocpRTwOS7vIFwURMR33XWXLjhMEDwXh0dG8FD0HXfcMSWHa8C5S0rBRLjmkgsLw6QUsCAgSgjmQuHapwPwubmhge2xiMwNNWyPBWFurKAuFhQ+N3Xso+v5EC4WM3KrTz79tObeEUEWFRdrhHVhSiEzI0Ol+4tf/UpF8OBXv6qyu+6aayQkNFR+++qrmoPFJeHPH3vMJlxEv1+55x5JSkyU//z+96cIFzdNr7j8cvn5L34hX7z1Vs0V474B8sP4pY2nnn5aUwfICSKvefWVV+rD9yi4sXfH7bfL//7859OmE1DXCuFivCF+3BTSv8EwMWG7L2Dytpp3RdR7PscLjqiHbSFi+5TC0PCw3ljEvJlpSsFE1e6cUvjzP/9zvYeEq2PcoLXP4SJnj3QmgrlLpUQWVIT78MMPawQLmeBGCZ4kwE0zpA/MWQWXgpgQ9jlc/AYbnkZAGgEF0QgmC/bx1ltvqXCwT9yQQ74PMjfiQX3IGTfh3CmHa0RnL1yTUjARhH2EayIYk5c1kQp+NjffsE9z4wQMTV2wgaBNRDvfwsVxIp20cf16jepxEwjiTE1J0Uv206dP2yLc995/X9MKuHOMghMnngxAhHz95z4ni6Kj9f0Pdu3SJx1MhAvhImq560tfsgkXkWlbe7uMj43Jrg8/1Aj6W9/4hqYcwASiePCBB+Snjz4qd991ly2He+cddwhSHnhiwp2Eq1csuFIKCtK8q/1NM7w2Tw/4+PpK6PkbpvY3SU2e11zxGMmYOrj0NldFJseL4MCkC0yay+R9zVWbM+mEuYpwIVPzJwZw8sZ9AnPTDJEthAsueI05ZYR733336YkK7+PKGldHFysLSriOoil3+Hwun1Jwh/7N9BjmIqUw02NYqPXnKsJdqDwuPG5XpxSs4ELhupgyhTsVKIX72ScYhTs9Owr3D3zm5BcfPvvUtW5LCpfCddVso3ApXGfnEoXLP16jc4URrrNL5tP1KFwK19nZQ+FSuBSus6vlEvUoXM8TLm4I4qko3OSflz9ek52TIw88+KA+T+spBY/M4MHo1197TaE6KgmJiRJg9yu0juovtM/x1ERTY6PTf4A8OCRE75g7e7d6ofFw9njN3zXAnf7Dhw45/Et63vb3cJ39A+T/9YMf6OODeDLHHeYUnqzBU0P42w3PP/uss9Nh2npOR7h4/u+ee+/VR3luvfVWlzQ+3zt5++239QwG4dbX1Tk8HAgGzznisRL8koYnFTxmg8eEOtvbnfpbxzj5gAf44W9WeHPBb0zi0Ss8X+zMV+zoH4dx4ls1PIUpvv/PmV8BxjPWSSkp+ges8MjWfBacRN977z191v2N116b0ffVTXfcTgsXO4kBiPXr9feQPaG8/vrrsm/vXn0W2Jlvb9BfZggKUg54ztiTCn4LcPD8d3M50y9EIJFRUZKZleVxLJzpv32dpqYmvTI4293t1DzCtuYXEjz9SyTxXK+z0SrWF35JYdvll0/5a3IzHQ9X1Mf4vPvuu3Jw/37940auKjMSrqsa5X5IgARIwBsJULjeOOrsMwmQwLwQoHDnBTsbJQES8EYCFK43jjr7TAIkMC8EKNx5wc5GSYAEvJEAheuNo84+kwAJzAsBCndesLNREiABbyRA4XrjqLPPJEAC80KAwp0X7GyUBEjAGwlQuN446uwzCZDAvBCgcOcFOxslARLwRgIUrjeOOvtMAiQwLwQo3HnBzkZJgAS8kQCF642jzj6TAAnMCwEKd16ws1ESIAFvJEDheuOos88kQALzQoDCnRfsbJQESMAbCVC43jjq7DMJkMC8EKBw5wU7GyUBEvBGAhSuN446+0wCJDAvBCjcecHORkmABLyRAIXrjaPOPpMACcwLAQp3XrCzURIgAW8kQOF646izzyRAAvNCAML9/3mWscRIwDmPAAAAAElFTkSuQmCC');
INSERT INTO "public"."AdminThemes" VALUES (2, 'Day', 0, '{"common":{"black":"#000","white":"#fff"},"type":"light","primary":{"light":"#7986cb","main":"rgba(56, 160, 160, 1)","dark":"#303f9f","contrastText":"#fff"},"secondary":{"light":"rgba(241, 188, 145, 1)","main":"rgba(240, 126, 55, 1)","dark":"rgba(151, 81, 36, 1)","contrastText":"rgba(238, 238, 238, 1)"},"error":{"light":"rgba(241, 180, 180, 1)","main":"rgba(201, 68, 58, 1)","dark":"rgba(156, 26, 26, 1)","contrastText":"#fff"},"warning":{"light":"#ffb74d","main":"#ff9800","dark":"#f57c00","contrastText":"rgba(0, 0, 0, 0.87)"},"info":{"light":"#64b5f6","main":"#2196f3","dark":"#1976d2","contrastText":"#fff"},"success":{"light":"#81c784","main":"#4caf50","dark":"#388e3c","contrastText":"rgba(0, 0, 0, 0.87)"},"grey":{"50":"#fafafa","100":"#f5f5f5","200":"#eeeeee","300":"#e0e0e0","400":"#bdbdbd","500":"#9e9e9e","600":"#757575","700":"#616161","800":"#424242","900":"#212121","A100":"#d5d5d5","A200":"#aaaaaa","A400":"#303030","A700":"#616161"},"contrastThreshold":3,"tonalOffset":0.2,"text":{"primary":"rgba(0, 0, 0, 0.87)","secondary":"rgba(0, 0, 0, 0.54)","disabled":"rgba(0, 0, 0, 0.38)","hint":"rgba(0, 0, 0, 0.38)"},"divider":"rgba(0, 0, 0, 0.12)","background":{"paper":"rgba(238, 238, 238, 1)","default":"rgba(245, 244, 244, 1)"},"action":{"active":"rgba(0, 0, 0, 0.54)","hover":"rgba(0, 0, 0, 0.04)","hoverOpacity":0.04,"selected":"rgba(0, 0, 0, 0.08)","selectedOpacity":0.08,"disabled":"rgba(0, 0, 0, 0.26)","disabledBackground":"rgba(0, 0, 0, 0.12)","disabledOpacity":0.38,"focus":"rgba(0, 0, 0, 0.12)","focusOpacity":0.12,"activatedOpacity":0.12}}', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAVwAAAGQCAYAAADiPNjjAAAgAElEQVR4XuydBXgUV9uGn1mJh5AQwUOQ4O4OxbUUaAuFUrxUqVGh/tX+9qt9daRCCxQoFHeX4q7FEiQJkIQAcdnd+a/3hARSIUvZTEN45rq4SHbPHLnPmXveeWc2q+m6roMbCZAACZBAgRPQKNwCZ8wGSIAESEARoHC5EEiABEjAIAIUrkGg2QwJkAAJULhcAyRAAiRgEAEK1yDQbIYESIAEKFyuARIgARIwiACFaxBoNkMCJEACFC7XAAmQAAkYRIDCNQg0myEBEiABCpdrgARIgAQMIkDhGgSazZAACZAAhcs1QAIkQAIGEaBwDQLNZkiABEiAwuUaIAESIAGDCFC4BoFmMyRAAiRA4XINkAAJkIBBBChcg0CzGRIgARKgcLkGSIAESMAgAhSuQaDZDAmQAAlQuFwDJEACJGAQAQrXINBshgRIgAQoXK4BEiABEjCIAIVrEGg2QwIkQAIULtcACZAACRhEgMI1CDSbIQESIAEKl2uABEiABAwiQOEaBJrNkAAJkACFyzVAAiRAAgYRoHANAs1mSIAESIDC5RogARIgAYMIULgGgWYzJEACJEDhcg2QAAmQgEEEKFyDQLMZEiABEqBwuQZIgARIwCACFK5BoNkMCZAACVC4XAMkQAIkYBABCtcg0GyGBEiABChcrgESIAESMIgAhWsQaDZDAiRAAhQu1wAJkAAJGESAwjUINJshARIgAQqXa4AESIAEDCJA4RoEms2QAAmQAIXLNUACJEACBhGgcA0CzWZIgARIQLPb7XpmRgYcDgdpkAAJkAAJFAABk8kEN3d3aOlpabrdbi+AJlglCZAACZBADgGL1QotJTlZJxISIAESIIGCJSBRLoVbsIxZOwmQAAkoAhQuFwIJkAAJGETg74WraQZ1gc2QAAmQQBEloOfN1lK4RXSeOSwSIIFCQIDCLQSTwC6QAAncGQQo3DtjnjlKEiCBQkCAwi0Ek8AukAAJ3BkEKNw7Y545ShIggUJAgMItBJPALpAACdwZBCjcO2OeOUoSIIFCQIDCLQSTwC6QAAncGQQo3DtjnjlKEiCBQkCAwi0Ek8AukAAJ3BkEKNw7Y545ShIggUJAgMItBJPALpAACdwZBAqrcOXbJuQPO3AjARIggSJDwAjhHj58GBkZGbBarShbtiyKFy9+Q36TJ0/GsmXL8L///Q9lypRxinVWVhYuXLig6r/RlpSUhHPnziE8PNypev+uUHJyMo4fP67etlgsKFWqFAIDA2+pTu5MAiRQxAkYIdz77rsPDzzwAC5evIglS5bgyy+/RMmSJf+W7MiRI/HFF1/AXb7vx8k/CxkbG4tJkybh5Zdfxttvv40+ffqgVq1af2pDyvzyyy9YsWLFLc3szp078corr+Dhhx9Wol+0aBF+/vln+Pr63lK93JkESKAIEzBCuA8++CB++uknRXHdunX44Ycf8O2336qUwZo1a3DgwAG0atUKdevWxffff6+EeM8992DEiBGIjo5W0a6bm5uSaEBAgKqrV69e6udZs2ahSZMm8PLyUsJt164d3nvvPVSrVg1jx45FuXLlcmdP13UMHToUVapUQbdu3dCwYUP13tdff43Q0FCcPHkSNWvWRPv27XHmzBmcOHFC/S/boEGDVB9yNhHuxx9/jKlTp6pxPPXUU3jppZcQEhKixrN27VoV8fbr10+dOGRMEuH7+/ujbdu2RXhFcWgkQAJ/S8Bo4UpqoXv37pg7d66Skvz/yCOPqPSB/LPZbBg3bhw++OADFQU/99xz6N+/v0oDbNu2De+++y4GDBiA//73vwgLC4NEw8OGDVMSFeE+8cQTSnwiZBGnyC5nS0lJUe8NHz4c77zzDmbOnKlkKeVE5h07dlSSFpGmpqZi/Pjx+Oyzz7B+/XrEx8fj9ddfzyPct956C6+++qo6KchJYMqUKZBUg/RZBLxhwwYkJiaq/fr27atOBr1790aFChW4IkmABO5EAkYLVxiL2CTik0tySQFIJCiRokSgEtWKRCWPK9v+/fsxceJExMTEwMPDAz/++OMNhSv1ibAHDhyIBg0a5JlSSVNIxNu5c2c0bdoUCxcuVJGtCFfSHDVq1FCpBklPVK5cWUXfIl2RrZwkRLyenp6qTolwRaQi6ISEBCVvEa6Pj486MUikfvbsWRV5z549W41JonpuJEACdzABo4Urkapc1ktk+/jjj6toLydP27x5cyXjHOHKV7WPGTMGL774IoKCgpTcJIq9UYT7d8KV6FbEKpfzUpekKaR9iTyvF+7mzZtx6NAh1K5dW0XgEhFfvnwZnTp1wurVq1GsWLFc4V6fUhDBirxLly6N1157DR999JGKfCVSnzNnDkaNGpV7ErmDlxuHTgJ3NgGjhPvNN98gMzNTRatyGS9RqORa69SpoyR4/vx5JSuJCHOEK5f1jz76KD755BOVXxWJTZs2TaUQ5J/sK0IWEeekFES48q9Lly5o0aKFeoJAtu3bt6uIWtIWInh5qkF+lkhahCuSlJyuRLSSXpBIVaJuSWEcPHgQ77//PubNm5d7cpAIV9Iasr+kQT788EN1Y1CiXXlN6l68eLGKbn/99VcK984+zDh6EsgmYIRwe/bsibS0NPj5+eHee+9V/0SEkt8Uoe3du1fJTvKhkja4PqUg8pL0Q4cOHVQeV+QrAhR5ipxFyiLv64UrEarkUSW6lEhVNvlZxC6phJxNbuaJaEePHq3SD/L4Wv369fHGG29g9+7dSriXLl1SJwrJ5cqjXzmbCFf6KTfBRM5yE06eWJDnh0XOkr8VkcuJ4quvvlInjpw0CdceCZDAHUrACOEWdrTXpxRy+rp169bclEJh7z/7RwIkcJsQoHChnlqQiLlixYq5syY36yQNIVEsNxIgARJwCQEK1yUYWQkJkAAJ5E+Aws2fEUuQAAmQgEsIULguwchKSIAESCB/AhRu/oxYggRIgARcQoDCdQlGVkICJEAC+ROgcPNnxBIkQAIk4BICFK5LMLISEiABEsifAIWbPyOWIAESIAGXEKBwXYKRlZAACZBA/gQo3PwZsQQJkAAJuIQAhesSjKyEBEiABPInQOHmz4glSIAESMAlBChcl2BkJSRAAiSQPwEKN39GLEECJEACLiHgtHBd0horIQESIAESyCEg336jpSQn60RCAiRAAiRQsAQo3ILly9pJgARIIJcAhcvFQAIkQAIGEaBwDQLNZkiABEjgb4XbYfZs0iEBEiABEviHBLwsFizs0yfP3hTuP4TJ3UiABEjgRgQoXK4PEiABEjCIAIVrEGg2QwIkQAIULtcACZAACRhEgMI1CDSbIQESIAEKl2uABEiABAwiQOEaBJrNkAAJkACFyzVAAiRAAgYRoHANAs1mSIAESIDC5RogARIgAYMIULgGgWYzJEACJEDhcg2QAAmQgEEEKFyDQLMZEiABEqBwuQZIgARIwCAChgl3+t13w+ZwQL63Jy41Fd/t24fD8fF5htm/WjVEJSVha3S0QcMHPuvcGb9FRWHm4cO31OYXXbqguLs7shwONb7Pd+7E2cTEW6qTO5MACRQtAoYJ9+uuXfHEihXQAFT298ebbdrgoYULkWazKaImTVP/dF2H/Q/fanmzyKUNZ76QTcp92bWrqv6xZcuc2ufv+iLCfWXdOqRkZaFTWBg6VKiAZ1evvtmuszwJkEARJmCocB9Ztkyh9HVzw9S778bg+fPxaadOiElKwprTp1ElIACnr1zB/thYfNapk4o8q5YooSJGEbOfu7uKGr/ctUsJrWOFCjifkoKyvr74z6ZNKO/nh/EtWqj9JYJ+pkkTvLRuHQK9vPBIgwZ4a9OmP0XUGXY7WpYtizc2bEC63Y5mZcpgTP362HD2LKqVKIHFJ05g/ZkzmNuvH1ZERsLLakUJLy+8vn69imZzNhHuy+vWId1mw7C6deFhseDT7dtxb7VqqBUUhEsZGXAzm/HBli14olEj1A8JwZ4LF/Dtvn1IzcoqwkuMQyMBEsghYJhwJ/fogcl796oo9q7QUFhMJiXJr7p2hYhYItvR9evnCnds48Z4ce1aeFutmNi9OwbNn6/6/HnnzipSDvXzU/KTep5o2BDf79+PxMxMtCtfXglZXp/cvTueXrUK91avjkNxcUrgOZvIb9F992HM0qWoGRSk0gE/HTyohNu6XDn8d+tWlC9WDBO6d0fPmTPxQ69eGLVkiRLqqy1bYsLevYhNSckj3GJubipKljGOX7dOnRwq+furqF76+nijRqq9xxo2VCeRGbeYxuAyJgESuL0IGCbcb3v0wA/796s87qkrV5Rw5Of/de6MsStWKGrXC1ci0tc2bFCvf9mlCx5bvlz9LBHxUytXQvK9DUqWVNKS/WYdOYKLaWloXKqUakc2EduFlBSMrFcPQxYsQGxqau7s1AgMxP86dUKf2bOVWEX8XWfMQP2SJdG0dGn8b8cOFHN3x/z+/VUZyfWOXrIEEhHfV706Ii5fxs5z5/IIV1IKyVlZqBMcrKJYEfToevWUbJdFRCjhPrF8OcY0aKBy1XOPHr29Vgt7SwIkcEsEDBOu5HBzUgrX9/ifCPfplStV5PnFzp04EBeHTzt2xJyjR/8k3NI+Pvi4Y0f1+uPLl+fJ0Q6vWxehxYrhUnq66k670FC8vnEjPC0WtClXDh9s3YpyxYpBIvMeM2fi+549cyPcV1q2xHf796tUSM4mKYUX16xRwpXUyJutW6sc9UcdO6oTikS+E7p1U/2gcG9pzXJnErhtCdyWwpUIV4RZOyhIpSBElpJGiElOzhPh5qQgJu7Zo8Scs5lNJkzo2hUjlyzJfa1t+fKQqFfyqiJUiZwlzyr52wXHj2PxffepHK5D11EzMBBPrlyJTLs9j3Al4pXXmpYpg9/OnlVR99NNmsDfw0PdCJToWyLtQbVqMcK9bQ8ZdpwE/jkBw4Rb3MMDl69Gk9d39/rXJV8rYsqy2+Ht5obEjAxV9PoyOT9LnlTyrtA0VV5uYNkdDljN5jw3od5r107lU69/akH2lRtwOdGttCF5VkkhVA8MRPMyZfDjgQNqn0tpaer/H3v1yn3qIDkzM/fpipyxSL/cTCZVVqQrfZefrSaTassmT184HGo/uaGW8/M/nzruSQIkcLsRMEy4RoORm2LvtGuHnTExmHnkiNPNy02znBzu9TtN6dUrN4frdGUsSAIkQALXESiywuUskwAJkEBhI0DhFrYZYX9IgASKLAEKt8hOLQdGAiRQ2AhQuIVtRtgfEiCBIkuAwi2yU8uBkQAJFDYCFG5hmxH2hwRIoMgSoHCL7NRyYCRAAoWNAIVb2GaE/SEBEiiyBCjcIju1HBgJkEBhI0DhFrYZYX9IgASKLAEKt8hOLQdGAiRQ2AhQuIVtRtgfEiCBIkuAwi2yU8uBkQAJFDYCFG5hmxH2hwRIoMgSuCnhfnP1q2uKLA0OjARIgAQKkID8fewRtWrlacFkMkFLSU525pvGC7BrrJoESIAEij4BCrfozzFHSAIkUEgIULiFZCLYDRIggaJPgMIt+nPMEZIACRQSAn8rXNvPzxSSLrIbJEACJHAbErC6w9L/PedummV90OE2HCG7TAIkQAKFhICbJ6xPLaJwC8l0sBskQAJFmQCFW5Rnl2MjARIoVAQo3EI1HewMCZBAUSZA4Rbl2eXYSIAEChUBCrdQTQc7QwIkUJQJULhFeXY5NhIggUJFgMItVNPBzpAACRRlAhRuUZ5djo0ESKBQEaBwC9V0sDMkQAJFmQCFW5Rnl2MjARIoVAQo3EI1HewMCZBAUSZA4Rbl2eXYSIAEChUBCrdQTQc7QwIkUJQJGCZc3yDodXsCHsWAYxugndljCFa9/j3Q9sx1WVtqDJeib7n/eo1OQGgDQNez69s7H8hIdlk/WREJkEAhJGCUcB33fgjt0HJoSbHQmw2Ctu1nwADpOnq+CtOit1xGXr//EyAzBdq8V7Nl+Q83vf2jQEIUtAtHoVdsCr1sHZh+eR7QHf+wRu5GAiRQ6AkYJVy9/wfQZj+fzaNkOPSAUGiHVyrR6J2fhZZ4Hlj0NrT0JCAkHHqXZ6FnpsO0+C0gKV5Fxo67Xwc8A6Ct+hha1AGgZmfovsHQKzUHMlNh+vUlwG5T+zt6vQot/hR0aDDNewXQNKDtw3BU6wjt2Dpoa78EdMDR+3XApwRMqz+D3uIhaHNfUV103PcxTLPHAQ577hzqQRWB6h2hl6yaXWdmGuBfFnqbUVIVUCJU7a9dioLe7UUgOR561XbA8Q0wbZicR6ZKuBHboJ3eBV3q6PceTFNGQjdZoXd+GihVQ0Xm2o5Z2UKu3wfwKwlt/hvQLp4u9OuKHSQBEvgLAoYJt+1oJSQcXQ/txG9ARgp0Tz+g2wvQ1n4FPbACUL4BtM1T4Oj7LkzLPwTcPOFoOQym+a/Dcf/H0NZ9Ay3tMvSuL0CTqLVsHThqdIJp5SfQq7QErF7QNv8AR7/3Ydo4GXDY4OjyHExTHwVCqkAvUQHa6Z3Qmz4AxEVCO7AU+uAvgWX/zZZkn7eBVZ9As2dBbzoI2urP8hBT/dozF7p/eWhXYoCTW4CActD7vAVt9ouAlx8c3V6Aadrj2cI9sATa+aPQWw5VJxdEH7wm7/aPQg8oDy0lASheGtrOWcCJzdDL1QWsHtAunIDeejiw5ScgMEwJ17TyUyApTo2LGwmQwG1IwCjhCho9uApQrycQEAos+wAoXQMIawocWa3I6Q3ugWnNF9Dr9lISlqhU9ywOzS8Ejq4vwPTDcHUZrzfoC1yOhublD90nENrWqUCFxnDU6QGTyLvDE9mX/BKp5qQUPHyhNx0IFAuBXrwstJOboW3+EXqP8dAWv5PdfqN7AZNFiV47dxg4ufXajPoEwjHkG5h+GKUiYr3jWGg/jwX8y8DR6RmYZj6t+usY/gNM89+A3vzB7DEkxwMlq0IPbZCdRrm6qQg39iQQcwgQydbsDG3WOOi+gdCbDATcfbIj5lWfAu7eQIVG0FZ/fhuuMHaZBEggl4AhwpUo0K80tMht2WKr2VkJEhJtyqXzkTXZ/bGlQ5PIt34faGu+uCYnSTH0GA/T98OyhdvoPiA+EpqI74/CXf0ZHJ2ehukPwpV0AdKuQNu7QIldhPZH4cKrOPRer6tIWMk99dK1PoQ1gd77DdVHQFNRqGnaY4A965pwTeZs4c59FXqLIdeEW7YOUKo6sGNmXuFeTSlIfY7R02Ga/ni2bPcuyI64pc+nd1G4PF5JoKgQMES47t5w3P0mtD3zgKRYQCLJmMPQDq+Co8fLMG2bli3i4mVUusHR/7/QNk3OjjYl8lv2PvR+/wfsXagkqN/1GExzXgJCG/5ZuAvfVNLErtkqn6tLSkFyow37A8GVoe1bCF3SG2f3Qdv0fZ4IV0XE3V+CZrZCW/ifPFOsS05YItTki9l9rddbpUXkJOLo/wFMyz6A7uUPNOoPbcZT0Hu+CkQfgHZmLxxtRsK07hsgLiKvcONPZUe4kseu0x2mn5+C3mxwttQvHIfeZjS0dV8DFjdGuEXlgOM47mwChghXEMuNoYb9sh8Li9iandMUcZWsCsjrWRnQtv8MXI5RuU00GQDYMqH99r2KTCUi1VsNV5f72DELWnykkpDkgTVJSchle1hTaFt+zG5LokO5ESd1SB7UZFFPR8C/HBC5Vf2uHVyu0gzatunXRCgng8gd0C6eurYwrJ7Q243JvqTPyZ9a3LLzvEdWqTyxuonnGwRsnAwtKQ56r9eyZVq6JnB2L7R9i/LeNKvbG6jULLuNhLPZfZBxSpQtfZebfDGHs3O2WRnqRqM6YXEjARK4fQkYJtzbAJFepRX0Bv1g+uW5PE8n3LDrAeWupRSuKyjCzc3h3gZjZxdJgAQMIEDhXoOsV2kNXDwFLeGs8+Ql8i5XN/vJi+uFKze55KmELMn5ciMBEiABqCt0fk06VwIJkAAJGEGAwjWCMtsgARIgAUa4XAMkQAIkYBwBRrjGsWZLJEACdzgBCvcOXwAcPgmQgHEEKFzjWLMlEiCBO5wAhXuHLwAOnwRIwDgCFK5xrNkSCZDAHU6Awr3DFwCHTwIkYBwBCtc41myJBEjgDidA4d7hC4DDJwESMI4AhWsca7ZEAiRwhxOgcO/wBcDhkwAJGEeAwjWONVsiARK4wwncjHDvcFQcPgmQAAm4nIDJZIKWkpysvvmbGwmQAAmQQMERoHALji1rJgESIIE8BChcLggSIAESMIgAhWsQaDZDAiRAAhQu1wAJkAAJGESAwjUINJshARIgAUOFq+s64tPTsT4qCvNPnsSl9HT0qVwZXUJDUcbHByZNu7UZ0XUg9TIcJ7bAsetX6PGReerTgirC1LAvTJWbA55+wM22p+uwJyUhac9OXFw0F2nHj+ap3610GZTo0QfFmreC1T/g5uu/tdFzbxIggUJOwFDhTjpwAPNOnkS6zZYHi9VkQr2gILzevDk8LZZ/jMy+fRYcm38CMlNvXIebF8xtRsDUoM9NtXVp9XKc/34i7MlJN9zP5OGBwD73InjAgzdVPwuTAAkUbQKGCNeh6/j24EHMOJo3Ivwj2halS+O1pk1hNZtvkroOx47ZsK/95qb2M3d8wmnpXlqzAtGffXhT9Ytwg+8fBGimm9qPhUmABIomAUOEezoxEWNWr0am3Z5L0WIy4afevfHyunWIuHw59/XH6tVD38qVb452Ziqyvh4IZCRn7+fhA71uL8DhgLZjJuBTAo673wR0HabF7wBXzqtimocvLI/OAixuN27P4cDvwwfCdvnStf77FUed76bj6PhnkRkfhyqvvQuzjw8i3v8PUo79rsqZ3N1R+dMJcCtV+ubGw9IkQAJFkoAhwp3+++8qwr1+61u1Ku6rXh3j/yDc5qVK4e2WLW8KtuPgCtiXvJ+7j161PRBQDnBkQdv2M/RG9wJxEYDVA6jSCtrSa2XNPcfDVKPDDdtL3L4FZ959PU+ZUvcPQpkHh+PIs4+jWN36SD5yBGZfH5S+fzAOj304t2zJYQ8j8O5+NzUeFiYBEiiaBAwR7pBlyxCdfDX6BOBttWJskyZIysjA4hMn8kS4xd3dMadXr5uibZv6OPSYI3n20au0BgLKZgv3rsegbZgE3TcIaP84tF/HA8j+NLNWugYsgz+/YXun33oVSbu25ZbxqlQZpQcNg094NRx/6xWkHM1uu9TAB1UUfW7G1NyynhUro9LHX93UeFiYBEigaBIwRLhdf/0VWQ5HLsFXW7XCtuho1AkOxqpTp7D3woXc98yahhX9bi4izPq0N5CZ8vfCbfcItM0/QPcuAbR/BNqvL18r6+YN61MLbji7x8YMReb5mNwylca/iZhpPyD87f8i4sN3kbRvN3xr10XI3f1w4u3X8tRl8vBEjRnzi+bq4ahIgARuioAhwv10924sjIhQHZNHvzqHhcHHakWb0FAcjovDN3v25Ha6VmAg/teu3U0Nwv7bj3D8NuXvhVujI/QSodDsNsDiAW3DhNyyptbDYG4++IbtXVw0D+cmX4tSS9zVGRYfH5QZMhzRU39A0sH9qPj8Kzj9xcfISkhARkwU9KsnmBK9+6LU8DE3NR4WJgESKJoEDBHu/rg4PLthA+Rpheu3uypUwIHYWMSlXnuM64Fq1TCiVq2boq0nxcI2cQhgz7q2X3AV6N7+0CK3A1ZP6A36quditd2/XntszGyFZcx0aN4BN2zPnpKMo8MHwpGRkadcueEPI3bJAnhWqAj/Fq3Ve7akRET/+K0qq5nNqPh/n8KzStWbGg8LkwAJFE0ChgjX5nBg1MqVOJN04+dX5Xnc2T17wsctn6cG/jgXug7b7JegR+64qVnSKjWHpd9bksnNd7+Yrz5Fwool+Za7voBHhYqo9NGXSrzcSIAESMAQ4QrmKxkZeG3LFhyMj/9L6r5ubvi4bVtU9PP7Z7OSkQLb4vegn9ji1P5aeBtYuj0HuHs7Vd6RnoaYCZ/j8tpVTpX3rl0P5V94FWYfX6fKsxAJkEDRJ2CYcAVlhs2Gqb//jv3x8Yi8cgUZdjvC/PxQIyAAw2vWvPnI9o/zY8+CY9sMOM7shR4bAaQn5i3hWQzy8V6tfD2Ymw4AzNabmmHdbkfC4vlI2rUd6aciYLty7flhqcjs7Q330DB416yDoHsHwuTmflP1szAJkEDRJmCocIs2So6OBEiABG5MgMLlCiEBEiABgwhQuAaBZjMkQAIkQOFyDZAACZCAQQQoXINAsxkSIAESoHC5BkiABEjAIAIUrkGg2QwJkAAJULhcAyRAAiRgEAEK1yDQbIYESIAEKFyuARIgARIwiACFaxBoNkMCJEACFC7XAAmQAAkYRIDCNQg0myEBEiABCpdrgARIgAQMIkDhGgSazZAACZAAhcs1QAIkQAIGEaBwDQLNZkiABEiAwuUaIAESIAGDCFC4BoFmMyRAAiRA4XINkAAJkIBBBChcg0CzGRIgARKgcLkGSIAESMAgAhSuQaDZDAmQAAlQuFwDJEACJGAQAQrXINBshgRIgAQoXK4BEiABEjCIAIVrEGg2QwIkQAIULtcACZAACRhEgMI1CDSbIQESIIG/FW5GZibpkAAJkMBtQ8Ddza3Q95XCLfRTxA6SAAk4Q4DCdYYSy5AACZCACwhQuC6AyCpIgARIwBkCFK4zlFiGBEiABFxAgMJ1AURWQQIkQALOEKBwnaHEMiRAAiTgAgIUrgsgsgoSIAEScIYAhesMJZYhARIgARcQoHBdAJFVkAAJkIAzBChcZyixDAmQAAm4gACF6wKIrIIESIAEnCFA4TpDiWVIgARIwAUEKFwXQGQVJEACJOAMAQrXGUosQwIkQAIuIEDhugAiqyABEiABZwhQuM5QYhkSIAEScAEBCtcFEFkFCZAACThDgMJ1hhLLkAAJkIALCFC4LoDIKkiABEjAGQIUrjOUnCgz58QJrI2KQklvb2gAHqpeHWV9fMBRQhkAACAASURBVJzY07kiRy9dQlV/f+cKs5QicPz4caSkpKify5UrhxIlStw0GbvdjtjYWJQsWRJpaWnw8vK66Tq4w58JpKen4+zZs6hcuTI0TUNERATCwsLUz85sEyZMwIgRI2CxWJwpXmjKULgumgoRrofZjB5hYdh/8SLWR0Xhibp1Ydd1OHQdZk2DSdOg6zpsuq6kbDGZVOs2hwP61d/l9Zzf5T0pk+VwYOKBA3ikTh1Vj/wum/Xq/i4aQpGrZtmyZejatWvuuIS9CFR9Sd7VA1v+l9fMZrP6Xzb52SFzouuq7MWLF+Hp6Yn9+/ejWbNmqkxOPfK+/Cxlb7eD/9+c8Li4OEyaNAljx46Ft7c3pk2bhvvvv1/xFvYyBzI38vP1vwtreV32HTp0KKxWa+4+OXMh+xbWjcJ10cxcL9zIxETMPXkSo2rVwreHDiHU1xc7YmPxRpMmmHH8OLwsFpxNSkKjkBBU8vPDvIgIBHp4ICIxEc/Uq4dhq1fj3sqVsTcuDt1DQ5HpcGD56dMYWqMG9sfHIzEzU0m3sp8f2pUt66IRFL1qrheuzWbDnDlzULt2bRVZNWjQQInU398fW7duRUhICLKyshQEibSOHj0KDw8P1KhRA5s3b0bFihVx8uRJtGvXDgsXLkTNmjVx7tw5dOjQAWvXrkWxYsUgbbRs2bLogSyAEYlwFyxYoE5SgwcPxowZM5RwV65cidKlSyMmJgYtWrTAqlWrEB4ejsuXL6Nq1arYuHGjen3WrFlo3769iozlfynXp08fTJw4EaNGjSq0Jz8K10WLSYR7NjkZ9QIDsS46Gj3DwhBx5YqKbsv4+EDef7JePfxw+DD+06wZkrOysCcuTqUhagQEINjTE5/s3Yuv27XDx3v34v2WLfFbTAxOXrmi0hNf7d+PR+vUwef79iG0WDHUDQxUdYcVK+aiERS9an7++WclTdm6dOkCOcgzMzNx4MAB9OjRAyLksmXLqn9y8MslakZGhhKwRFEiV7n0Xb16tRLrvn371CXwzJkz0bZtW5w4cQI9e/ZUB7ukLMqXLw8fF6aRit6MXBuRzMX69evViUwi00OHDqF79+7q5CViXbp0KR599FGcP39eXUHICbBJkyZITExUc5CTUpD93N3d1ZzJ1cepU6fyXNUUNoYUrotmRISabrejSUgIfjlxAuMbNcI3Bw6gXlAQyvv6qhSCj9WqpPpakyaqVUkjPLl+PYbXqIGQq7lBf3d3vLl9O95r0QJbz53D4YQEjKhZM1e4ss/+uDhMO3YMXcuXx13lyrloBEWvmusj3KSkJMyePRtDhgxRghQBizh9fX3RrVs3TJ48GcOHD1eC3b59+98KV6Kt5cuXY8CAASqNIFGxXPJKtLxhwwYMHDiw6IEsgBHlCLd///5qXiQ/fvfdd+Pw4cNKnML2zJkz6ndJC0nkW69evT8JV9I8fn5+KlcvVyLCX34vrBuF66KZyUkpdA8LU6KVqLWklxdWR0WhX6VKWBARgYFVq+LL/ftxf5UqOHb5MlKysuDn7o7o5GR0LFcO048dwyO1a+M/fyHcd3fuxON16uDTvXvRu2JFZNntWB8djecaNHDRCIpeNdcLVyJbSSnITS+RpBzockBLhCTClZ937NihRCvRq0TB10e4nTt3znMZe+HCBQQGBqrLW4nGpP5q1aqhVq1aRQ9kAYzoeuFGR0dj/vz5GD16tEoZXLp0SaV4JJ2zaNEiBAQEKAFfH+F+9tlnqFChguqZXK3I+1OnTlV53cK8Ubgump2t58+rm1gNg4ORZrNhYWQk+leujOVylk5IQLOSJdGyVCnEpKRg1vHjCPT0xH2VK8NqNqt876nERHQNDUV48eKYefw4BlWtqqQclZSkoljZJ8DDA42Cg/HzsWPqBtzgqlXhbbW6aASshgRuXwKpqanYtWsXWrduXagHQeEW6ulh50iABPIjIOmI77//XqV5JBouzBuFW5hnh30jARIoUgQo3CI1nRwMCZBAYSZA4Rbm2WHfSIAEihQBCrdITScHQwIkUJgJULiFeXbYNxIggSJFgMItUtPJwZAACRRmAre1cAszWPaNBEiABG5HAuqPO6UkJ8unWrmRAAmQAAkUIAEKtwDhsmoSIAESuJ4Ahcv1QAIkQAIGEaBwDQLNZkiABEiAwuUaIAESIAGDCFC4BoFmMyRAAiRA4XINkAAJkIBBBChcg0CzGRIgARKgcLkGSIAESMAgAhSuQaDZDAmQAAlQuFwDJEACJGAQAQrXINBshgRIgAQoXK4BEiABEjCIAIVrEGg2QwIkQAIULtcACZAACRhEgMI1CDSbIQESIAEKl2uABEiABAwiQOEaBJrNkAAJkACFyzVAAiRAAgYRoHANAs1mSIAESOCWhfvtt99CvhAtKDAQ7du3R7FixRAdHY2ly5bl0g0KCkLLFi0wb/783Nfq1KmDJo0b49ChQ4iJiUGnTp3Ue0eOHMGpU6fQrVs3pKenY+bMmejbty8OHjoEXx8f1KpVCwkJCfh17tw8s1c1PBytW7d26YzOP3kSqTYbzJqGekFBCPf3x9FLl7A7NhYmGbOnJ1qWKQOLyYRFERFoUrIkPC0WLDt1Cp1DQxHg4aH6s/PCBcQkJ6N7WJgqm2m3Y0lkJNqWLQv/q2XWR0UhJiUFVpMJ1QICUCMgACtPn0bF4sVRpXhxJGdlYfWZM7i7UiWXjhGZqXAc2wj5XytXF1pQRegXjkM/tfNaOyWrwhTaAPqlKOiROwGrB0xVWgIevqqMHnMYevRhwL8MTBWbACYzHAeXQysWAq18PVXGsW8RTHV7Qo+LhB6xVZXRgqtkv69p2fUkX4R+ZA1M9XoCVk9Ad8CxfymQnghY3KFVaAjNyx+O/Uug1e0BzcMX+vljQHI8tMotXMpF1qTdbofVakWJEiXU/zabDRcvXkRISIhqS9ZhamoqvL294e/vn9u+vC4HVvHixdVraWlpiIuLg6ZpcHNzQ2BgIMxmM86ePavqktdyNnlN17O/YlBeL1mypDqeHA5Hnn1dOti/qWzWrFm47777ct9NTk7GkqVLcd+992LhwoWoWLEiatasiczMTMyZMwd9+vTBwYMH4eXlpV6X43jHjh3o37+/Gjs3qHVxS18i2bhxY4x55BHs27sXMefOYdrUqdi9Zw9efPFFjBgxQi0skXGZMmXw/Asv4IEHHlDca1Svjnr16mHUqFGIiorC0qVL1aTMmDkTq1atwuRJk9SC7tK1K+bNnYuffvoJpUqXxkNDhuDy5ctYvGQJTkVGYvPmzXhg0CBUrlQJTZs2demcDli8GPeGhyvZLTh5EhM6doSIcWN0NFqULq2k2b5cOQysVg0PLVuGZxo0UJJ9eNUqPN2wIXqEhan+PL52LS6mpeH7zp3hYbEgOjkZo1auxCN166JXxYqqzEubNqG8ry98rFaI6L/s0EGJO/LKFbzRvDmmHD6c+7MrB2lb8gG0jBQgoAwch9fAOmyS+t+xaw5MDfqqprSQStBKVkXW9yNhCmsCJMZCt1hg6f0a9KgDsC18G6Zq7aEf2wBTvd4wNR0A24+PALZMWIZOAEwWZE0aAuuoH+E4sByO3b9Cq94e+t5FMDW4B6ZG/bKlfHAF7Cs+gWXgJ9BKVQPsNti+Hwmtapts+e5bDOuwycia9gTMbUfDFN4atomDYWr3MEzV2rkSC7Zt26bWrKw1kV3t2rWRkZGBw4cPo0GDBipIiI6JQcmQECXEsLCwXBHv2rULdocDjRs1UmtaJH3mzBlI4HHhwgVVrmzZsti4caM6Bnx9s09csv3222+oUKGC+lkkHxwcjC1btqBcuXLqeLBYLKhevbohAuvatSuWXRc4yZhHjByJpUuWYNDgwWosixYuVCeiXr1745dfflHHqRzvPXv2RI+ePfHmm2+iY4cOLp2b27myWxZuy5YtsWTJEvj4+ODxJ57A8GHDYLPb8e6772LO7Nm5Z2+JZD/+5BN8O3lyLi9ZzBK91qxVCwMHDkSL5s2dEm5OBbIQJ02ahO+++65A5mDAkiWY0b27qvv9HTuUEN3MZhWJPlGvHk5euYIv9+7F/7VunUe4H+7ahRAvLyVKKfv8xo3qAMwR7tf79sHdbMapxET8p0V2ZCbCfahmTVTz98fEAwfgYTbj/qpVMXrVKnzcti2eXb8ezzVsiFqBgS4dq23CA7AM/BQoFgzHiS3QSlWHfnQ9HEfXKfHlbI6t06AnJ8Dc8QklP/vi92Hu9hxsU5+AqUEfmGp3hZ4UB/svL8Iy/FslXP3KeZjq9IC57ci8wo3YBsvdr6n37XPGwzI8e/7sc1+HVq4O9PQkmFsNzRWuud/b0IqXgW3GszBJZBtcGfbF78Hc8XHYZz0Py6O/AO7eLuUiws05gUvUVqpUKRXJ5gj3wIED8PH1RViFCkhMTFRSlohWosCIiAgkJSejYYMG8PDwUMKNj49H1apVceXKFRVgSAT4V8KVNd28efM8Y7n+tT179ii550TPLh30Hyq7kXAHP/igOtFIADVwwIA/CVeYydhfeeUVdZLglk3AZcL18/PD1998AzerFTVq1sS4ceOUTCXC7XvPPWpRPv3MM+jerZtqWC4zzl+4oM6Kkm5YsGABJk6ciFm//JJvhGukcCd36qRSAG9t24Y+lSohPi0Np5OSMLJWLSyOiEBEYiLGNWqUR7jfHTqEDJsNb7VsickHDyI1Kwt74+KUcB0Ahi9fjv+1b4/Xt2zBZ+3aKYmLcO+tWhWhvr74786dKv3QpkwZzDh6FJuio1Xq4a2rcnbl4pVLf/vG72Cq1AKmWp2hla4Ox+75sG+fAVPN7DSPuflg2Ba9B1OZGjA1vvda85lpyPpuOCy9XoZWppZ63TZhECwPT1PC1crXh+PQSlge/AK2meOuRbhXhavKTxwMy+ip0FMvwz57PCwDPoJt2pOwDPk6u77vR8Lcczzg5Qf7rBeU5LUyNWGbNlalQUxNB8JUw/UR1PXCPXHihDpQSpcunSvcpKQkHD12DJ4eHioKlTSBRLO/Hz0Kby8vdZktkau8J8KVy+uAgAAVpYaGhqryfyXcTZs2qchaNjmmZJ/rhSuBi7wuEXJBb/kJd9CgQepK9Msvv8TABx7IjXDlqlOi4XVr16oonds1Ai4VrkSwcrkkuZ1XX30Vr7z8sjq7Sd5Vzoavvf46xj75pGpdcrjyu1x2yeJ75513MH/+fCXblfmkFIwS7v2LFyvZyoHUrGRJPN+4MeYcP64k6ia5WIcDEzt2RIi3dx7hfrlvH2qVKAFvqxULIyLwUI0aEAmLcEW8H+3ahZebNcMvR4+q1ISkHkS4hy5ehM3hQP3gYLzTsqUa5vnUVDy4dCk+bdcONUuUcO3alVyhPRPQzLBvmQrH3gWwjPge+pF1cOxbCFPbh7PPyhXqq4hWC66k0gVqkzSEyZwt3G7PX83V6rBNGJwrXFO9XkBmOhwJZ6Gf3gnrqJ+yUwo5wtV12CaKoKfDsW0GHKf3wNR8EBzLPoK50xPQytVTwtVTLgG2DJV6MLcdpZqX9INjy1RYRk7JzQG7Es71wj12/Djc3dzU2s6JcCWilXUhkasIuXz58irfKukE+VkOLJGOpAxEuPKzpAXkZ8kNh4eH/6VwRVbVqlVTQ/H09FT/rheuRI4iYZF/QW/5CXfcc8+plN6Bgwdx+NAhzJ4zR6UUJIiSeyo1atTAc889Z0j6o6BZuKp+lwlXItl+/ftj0sSJKreVX0rhQmysSrIPGDAAHu7uWLV6NZ4fN05FAJ9//jnmzZuHkydP4qGhQ1WeaPLkybk5XKOEKykFydvKTTMviwUmTVPClVTAA9Wq4Yk1a/Bas2aoVqJEHuF+umcPxtSpg/GbNqkUwH3h4fi/HTuUcCcdPIjEjAyE+vnhXHIyjiQkYFLHjnhl82b0Cw+HSdeV0L+6mvdKs9lwz4IF+LpDB4T5+blq3lU9ekYy7LNehGXAh+pGmESh5vZjoEcd/HNK4chqOH5fB8s9b0G3Z8E+/SlYBn8O26+vQStZBeaWD8Fxchsc22fCMvBjFeGKcCW3apsyBnrqJVjHLswjXMeRNXDsWZAd1U5/ClpQGFAsBPq5I+rmmLnT2OwIt8eL0C+fg350A8x9Xs/u+9kDsK/9GpYhX0qW2aVcpLIc4YpYRaIiD1njItz69eurm0MiPbmhFhkZqfKYEnXK6xLVyo0vuadRr25dddMsJ6Ugke/+/fvRqFGjm04pSF/kJpQEKyLigt6cEa6cRLp266bGuHbtWiXc4n5+aNeuHfr264fp06ej+tUTSEH393ao/5aFK4uvSZMmSExKQvNmzfDYY49h+44dGDt2LBo1bAjNZFILsXevXnlyuHPnzcOMGTMwfdo0tZDXrFmDRYsX48033sCLL72EjPR0pKWno23bthg1ciTef/99bNm6NfdS6vPPPlMHhVE53JzJFOHm5HCXnzqF32Ji8EqzZn8SrkSkQ5cvx5P16qmUgQj3u86d8diaNfisfXt1cywhPV2VEal/tmdPbg73ra1bUT8kBD3DwlCQwlWRokSWJzZDc/OC7rDD0vctJUX7bz/AVLqmGrZWsbG6GWZf9K7K08rNMEk3mBreAz0pXuVTIdFyRrISthba4Jpw63RXN+HsKz6G9alF2XVv/FZFyxIly80vLTAUth8ehmXEd0r8ekIU7PNeg+WhidnCVTnc0rBNeQSmNiNhqtjYEOF6eXsjMyND3eySqFWemsmJcHNuhMkls9xMqyTppvh4dYc+J/oU+cpTO5L7PX78uLrPIXVIykBywhs2bFDvy1WgRMuS45VoNueJB3d3d1SpUkW9JvtKO1K3EdGtzLvcEG9y9Ua0HMtdunTJvWkmOVyJcOvWrYuVK1fi2eeeU8dwzk2zwYMHq/Tg4kWLMGHCBJXP5eaCHC4hkgAJkAAJOEfgliNc55phKRIgARIgAQqXa4AESIAEDCJA4RoEms2QAAmQAIXLNUACJEACBhGgcA0CzWZIgARIgMLlGiABEiABgwhQuAaBZjMkQAIkQOFyDZAACZCAQQQoXINAsxkSIAESoHC5BkiABEjAIAIUrkGg2QwJkAAJULhcAyRAAiRgEAEK1yDQbIYESIAEKFyuARIgARIwiACFaxBoNkMCJEACFC7XAAmQAAkYRIDCNQg0myEBEiABCpdrgARIgAQMIkDhGgSazZAACZAAhcs1QAIkQAIGEaBwDQLNZkiABEiAwuUaIAESIAGDCFC4BoFmMyRAAiRA4XINkAAJkIBBBChcg0CzGRIgARKgcLkGSIAESMAgAjclXLvdjqNHjyI1Lc2g7hVsM25WKypUqIBixYo53dDvCQk4nJAAm8Ph9D63Q0FviwX1goNRxsfH6e7qp3bBERcJ6EWLhdMAcgqazDAFVYQWWt/pXbOysnDx4kXIMVVUN4vFguLFi8Pd3d3pIZ45cwbx8fFw6LrT+xRUQavFglKlSiE4ONhlTTgt3MzMTJw6dQqhoaE3BdBlPS2AimSxywQHBgbC19c33xaOXboEN7MZ5Xx8YDaZ8i1/OxVIt9mw/fx5NClZEh4WS75d16MOAN7+0IqXBrSixSLfwf+xgO6AHn8KuHIOWuUWALQbVmGz2ZCYmAg/Pz+Yzeabbu522UGOr8uXL6uAxmq15tvtHTt2oGLFivD394eI6d/epP/nz59XbriZoOxG/XZauFeuXFGi9fDw+Lc5uLz9c+fOqTNZftvmmBg0LVmyyMk2Z9zxaWkqci/p7Z0fCjjO7oOpXN18y91JBRwHV8BU/S7AfOMTlsjW3cMD7m5uRR5PekYGsjIz8w1oRG6HDh1CnTp1ChWTtLQ0xMTEoFKlSi7pl9PClTOVmL4onpHlLFayZMl8gW6KjkaL0qVh0m4cweRbUSEtkJCejtSsLJR1ItqncP88iY4ja2EKbwWYbxzNybHk7e3tVNRXSJeK092SK+P09PR8I0RJsRw/fhw1atRwum4jCkr/T58+jSpVqrikOQoXUJcNFC5A4d7aMUXh/pkfhZuXCYVL4eauCAqXwr01AhRufvwoXAqXws3vKHHyfUa4FG5+S6VAhPvpp59C0zSUK18eXbt0gZeXF/bt24c1a9bk9qd58+bqkZGlS5fmvta/f3+UK1cOq1evVjmuZs2aqfcWLlyIkJAQNGnSRN31XLRoER544AHMmDEDUk9YWBhOnjyJBQsW5Blv27Zt0aBBg/wYuDylsD4qCscvXQI0DUGenuhUvry66zrn+HGkZWXBy2pF6zJlUM7XF+dTU3EgLg6dQkMx+eBB1CpRAs2u3sBLzMzErKNHcXflyqoe2baeO6dyyPI0gWwRV65gzZkz6ucgLy90KF9e5WF/i4nBPZUrq9eXnz6NQA8PNAwJuSGLAolwbVlwHFoJpFyEVr4etLK1oMefhuPQqty+aEEVYapxF/Qr56EfWQNY3KBVaw/Np4Qqo5/7HfrJrYB/GZiqtwdMFjiOrFZPA6ibVAAcO36BqWFf6AlR2e2ZTNBCqsBUpZWaB7WlJcK+aw7MDfsCnn7Z++1ZAD0xFrC6wRTaEFpQGBw750Cr3RWabxD0C8ehXzgBU51u+a4jVwtXcp9yw0YzmeDj7Y2goCDVB7npJpfq8nSNPPFw4cIF2Ox2BPj7596ckptQZ8+eVamynBvdsbGxSE5OVvX5FSuGgIAAVZ+Uk+MuZ5O6o6OjoV99NEueppAb5rK/7FvM1xclSmTPTX5bQaQUxA9WNze0ad06t/mpU6eiYcOGitH06dMxdNgw1c+tW7cqVvLejz/+iMGDB6sblj/9+CMaN26c70262yKHK6J75NFHsXrVKgQFB+Pdd97BzzNmKLn27t1bQapZowYiIiIwe84c9OjRQ70mAGURdOjYUT37NmvmTCXuJ8eORa1atTB61Cj1GNdTTz+t3ntg0CA89thjaNumjVqYm7dswe5duxB/8SI6d+6MunXqOJXsdnUO9/0dO5CclYVGISFYdeYMqgcEYHD16hixYgX6VK6spLsoMhI/dOmCM0lJmH3sGP7TogU6zZmDMt7e+K5LFyVVEfTX+/bhy7vuQtWAANh1HQOXLIGfmxsmduyo2KyLisKUQ4fQt0oVbIyKgqfVijebN8egJUvwTqtWKOvjg6HLl+ODNm1QOp+nDwpCuLaVn0FLigNKV4djx2xYBn6spGhf9iHMbUdnHzDFS8FUujpsPz0OU1gj6Bkp0BPOwvLAp9BjDsM27w2Y6/aA4+Q2aKWqwtxpLOwL3oIj+hCso6YAFnfYvh0Ky9BJ0CO2w77uG5ga9Yc8NSCCN7cbo6Srn94N25yXYe45Hqbw7IPVNvUJaBUaQLN4wL77V1gHfQ7b0v/CFNYYpsb3wjb9aZiqtYWpUb/83AJXC1eCi/3796s75CI7eTRJHpuSp2pEnOHh4Thy5IhaByJVEa+IRZ5/TUlJwZ49e1AhLAxly5RRfT98+LC66e3j44OzUVHqBpVIafv27SqYydlSJQg4cADly5dXL0nwI/KXoEaCqAvnzyux5bx/IzAFIdw333wT3j4+eO7ZZ3Ob7te/Px566CFUr1YN991/P5595hkl16+//hrJKSkY+tBDuLtPH/w6Zw527tyJiZMm4efp09XY8ut/ob9p1r1HDyxZvFg91D1g4EB8/NFH2PTbb/j9yBEIrJxt8eLF2LN3L155+eXc13bv3o2nn3kGnp6ekEi5WtWqTgk3p4Jff/1Vify5557L9wDJKVAQwpUPEIhkL6Wn44WNG/Fh27ZKuJ/fdRdKeHjg4VWrMKp2bXhbrbnC7T53LqwmE95t1QrVAgLw9Lp1kCj3pcaNlXAlan5m/XqU8vbGMw0bqjIi3CWRkfigdWucS0nBi5s2YUqXLpi4fz/i0tMRVqwY5HGvJ+vn/1B+gQh3wmCYuz8PrVwdOM7uh1YsWEWM9tWfw/rIzNw5cuyZD8fpPbD0eQPQddhXfApzx8dhn/cmtLK1YWp6P/S0RNimjIF1zHQlXP3sPiC0ASw9x+cV7vaZStYS0WZJ+ZFTAKs77Iv/D1rpGtDPH4O5W/b6EOGaujytPrig3peoOLw1bDPHwdz/PdinPgbLqB8Bj/yf0y4o4bZp00YJT8QoUdmlS5dyhSsRXP369VUEmpCQoCJceeY1KipKjU8+XFG3bvbjeyJcCWgk6pUPMHl5e6Nc2bJ/Kdzff/89z9WhCF+ewxcxi8zlirVRo0Zwy+fRtn9DuAMGDEDJUqUwZ84cfP/dd3mE+/L48fjvhx+qCPf6qP7vZHFbRLg5wpVBPPHkk+jdq5eKOmf8/DOaNm2qxjZ69Ghs27YNkydPRsNGjeApEnr4YfwwZYo6Q8fHxanF8eijj96Wwg309ET/8HBsjI7Gb9HReKlJEyXc91q3Vo/Fv7hxI/6vdWukZGXlCrfHvHnoWL48vCwWJeuXNm2C1HN/eLgS7uzjx3E5PV1Fa1l2Ox6pW1cJd8HJk3ijeXOsPXsWq8+cwWft26snDp5cu1bJVn4P9/fP9wRUEMJ1RO6AfeVnMJUMh1arM0xhTeA4/hvsS/4PplpdVZ/MbUfCvn6yXODD3PHJa/3UHbBNexLm5g9Cq5S9bmyThigBinDhWUylJiz3fwj7kveuRbg5wtVM2eUf+ga6PQv2aWNhGfI1bD8/Bcugz1XqQgm33WhoxUJgn/8GTG1GwhTaAPb5/4F+KRqmut1gqt8nX3ZSoCCF63A4sGnTJiVPEV5OhCsiPBkRAf/ixdWz5HL5L6kACVzkmdaDhw6poEUCGBGupB7kWJO0RO3atZUw/yrCFaFKFKtSg+XKqVRejnAlkNqyZYuKpqXe/CJEVz8Wll+EK0HeoEGDcCkhQZ1c5JOxORGul6cnataqhU8/+USNLb/tthPu6IcfVqG+pAI2bNigBi6bLAbJ6S5btgwDBw5Ukq1Xrx4GPvAAhg8bhti4OPW+nImeqhqXJQAAG5JJREFUeuopdfkjkpbw/plnnsHMP6QUCluEKzlUiV5Fns83aoRSPj5KuDLJyZmZGFqzJu4LD8f++Pg8Ee5Hbdtiwv796FOpkpLm3rg4DKpWTQn38TVrVEriSkYGVp45g286dFDCfX/7dvh5eKjXP27bVqUwZPvu0CFsO3cOEzp2zG9dqfddLlzJAWamKrE59i2GfdMPSo6Sq7Uv/xjmXq+odk3l68Cx4VuVSjB3eSa7r6mXVVRpm/EMzA36QqvWVkW+tomDYXl4WrZwAytAK1EBDsn7xkfAMmxydkohR7gi6AmDYBn+HRy/r1UpDVP7h+H47UeV7zXV6KCEK/1BVhpMVdvC3G2cal6P2Abbkg9gHf4d4JWd781vK0jhSq528+bNKppNSkpSwpVnQ0XEcn9A8rCSd5UIWIQsqYbKlSur9IPcQ5G0hAhXBCmBTGRkpLovIpL+K+HKhxBkf1mvEjVLpJwjXHlmVoIliXDz+yDUvxLhDhyo7gPdd++9KiL3K148V7j169XDgYMHVTqhzNVUS34njNsmpSCfiZazjaQX5vz6a74phaPHjmHcuHHo3y87XzZr1ixIMlyiYPnEx6uvvqpA/iSvTZqUJ4db2IQb7OWF+6tWhZvJBIvJpFIDIlzJpf5+8SJ2x8bi5aZN/yRcyddO+/13HL10CW+1aIFJBw5gSPXq6uO2r27ejN5XP/GyNDJSyXVPXBwWRkTgP82b4+VNm9AtLAxdKlRQOBZHRqobci9el5+70eJyuXAz02Cb8jDM974PrXgp2Oa+BlPtroDD8eeUQuR2JULL4C9UNGr76TFYH5oA++ovlLTN3V9QKQfH2q9hGToxV7jmFg/CNn2sSlNYn5yXR7iS83VsmASL1LPgbcCrOFCiPPTYE0BiHCz3fwDbtLEw3TUGWlYG7L/9BMsDn2QLV9Iec1+DZdgkwD3/T97JPgUpXIkwJa8qN4lzbn5JPlciUZGwSFd+FklKikzysPIR2YzMTBXpyc1jSRPkpBQk7SbirFq16k2nFKR92V/knt8Hof4t4e7auRMrV67Eiy+9BEkx5ES4v8yahRUrV2L9+vUq3ZBflHtbRLiNGjdGvbp1cSUxESOGD0fXrl3VTbNJkyahUsWKakH37NlTRbXX53BfeeUVBAYF4amxY1WZjz76CPInLIYNHYrxL78Mu82GpORkPPboo2jRooUSrpzh5XJKtokTJ2Lu3LmFKoebI7gc4UoOt5jVitGrVuG5Ro3UzbGcm2aSwxXhnrxyBd8ePKhysW9u3aqEKzffbLqOsVdzsdOOHFHpgrrBwbk53F0XLmDigQO5Ee2/LlyR0MHlKrqVG1tw2GDp9QocMUdgX/gOtHK1syPcUtVhaj0U9tVfQT93REWyWnhrmJsOANKuwLbso+yI154Fc4sh0Co3zyNc+SM6tl9fhXXsfCVciUy1kuHZ5VsOUU9H2CYPVeKFmyf0pDjYpj6uolfbLy/m5nBtv7yknnow1epUqISbkyaQp3HkZ7lBnJNSkFxtXFycEq7IT64E5WZZtWrV1A0hOT7kbxTI1aPc9JLoV/K9khaQm25SRlIVOX8rQCQtTyBIHTl/X0QkLamHY8eO5b4msnfm748UlHDlnlCF0FC1fsQbzzz7bO5NMwnyRLgyVvlZcuDX3zSTMd8/YABGjhiBvn373vDC5bYQbn6XXoXtfVffNCts43O2Py6PcJ1tuIiUc3WEWxSwFIRwjeRC4RYAbQo3GyqFe2uLi8L9Mz8KNy+TAvngw60tW+P3pnApXFesOgqXws1vHVG4/Ghv7hphhJvf4XLj9ylcCje/FUThUrgUbn5HiZPvU7gUbn5LxWnhyh8gl2f48vtkSX4NFsb3nU0pqD9AXqoUzE48MF0Yx5lfny6mpyPTblefZMtv06MOqo/NcrtGQD6EYarWzqk/QC7HkjPfgnC785UcbkZGRr5PNMhTE/LssHyEvzBt0nd5EsTwP0Auz/XJ4yfyqZPC8PUXrpgU+USOjEkeT8v5Qx43qlc+hFCpeHH4WK35fImKK3pnbB3yHVLyWFnNwED1YY38NkfUAWjBlaG53fiTRvnVUzTe16EnxUOP3HH1j9zc+BNMOTeS5LGq/J4DvZ35yPElH9KQIC2/D0jIOOcvWIBOHTuqD2oUhk36Lx+jlg+duOp7zZyOcAWARLkSDWbZbIWBxy33Qb6XzD8gACHBwU4t/CyHAwfj4xGbllYovuTulgFcV4H8DQf5wzny9xmckkBmqvpbBnrqFVd24/aty9sfpjK1nP6QhDwjKv9y/iLX7Tvwv++5yEUiefljOc5sEuXKp7rkQ07//ldIQn2VlpwUy5Yt60z3nSpzU8J1qkYWIgESIAES+EsCFC4XBgmQAAkYRIDCNQg0myEBEiABCpdrgARIgAQMIkDhGgSazZAACZAAhcs1QAIkQAIGEaBwDQLNZkiABEiAwuUaIAESIAGDCFC4BoFmMyRAAiRA4XINkAAJkIBBBChcg0CzGRIgARKgcLkGSIAESMAgAhSuQaDZDAmQAAlQuFwDJEACJGAQAQrXINBshgRIgAQoXK4BEiABEjCIAIVrEGg2QwIkQAIULtcACZAACRhEgMI1CDSbIQESIIGbEq7D4UBcfDzMZnORIJeVlYXgoKCbGs/m6Gh8vns3LheR73XLmcgavr54rXVr+Lm7Oz236fuWwbH2a1gdmU7vUxQLZsIN5g6PwKNuV6eHZ7fZcDEhQX2jbVHd3NzdEViixE0dX8kpKeqLJ//tbzSW75qTL4/0L17cqS/AdHYOnRauzW5HZGQkkpOTXfqlas52tCDKnTt3Tn1jb8WKFeHhhGi2nj2LF1esgG4yweLrWxBd+tfqzExIQAlfX0zr3x/eVmu+/Uj+7WckLPsKXm4m+Lnn/y2/+VZ4GxdISLMhPcuBEu2GwKfjqHxHIoGLfBmrHNBFfRPBlCpVyinpXr5yBWfPnlXf8uvMt2gXJDsR7oULF3L94O7m5pLmnBaufJPmyYgIpKenw8/PzyWN/9uVyJlUovXQ0FAUd2JM723ahMWHDqlvtTW5aAL+bQaqfU2DLTUVJosFP/Xvjwr+/vl2K37qC7h85DdYTRo8LSZVvjB802q+HXdhgZwvQ0/JdMCu6ygWVApBY2dAM934ClCOpbi4OBf2pHBXVaJECXh7e+fbyWPHj6tvMpbjy5ny+VZ4CwVEuBJcih9Kly6NoMDAW6jt2q5OCzczMxNXEhPVnosXL1aXQnKmvh03mVA5i7Zv3159hbOvj49Tlw3/2boV66OikB4bi+STJ+Gw22/H4efps0nToFmt8K9bFyZ3d0zo0AGVnRCubeY46Kd341BsKg6dT4Ndd9yBwtVg0oDGZX1QMcAD8A2CdfRUwHzjiD81NRXx8fG3/dpxdgDFixdHsWLF8i0u6UrZ5KvSd+/eDfna9H9rc3d3R7t27dTXpMvPxVx0RfuPhDtz5szbVrY5EyjS7dKlC/z9/W9auGnR0Ug6ceLfWgsF0m6JJk1g9vS8aeFuO5uEo3Hp0O843V6bhoZlfVAr2IvC/ZuVebPCPX78OHbu3Fkg69zZSiWy7dy5M6Tv/7pwZ8yYAQm5b+eNws07e/9UuFuVcNNu56Vwy31vWMYHtUIo3L8DebPCPXbsGHbt2nXL83IrFVzvBwr3Vkhe3ZfCpXBdsIxUFRTujUlSuNf4/KOUQn4R7sqVK1ULkiyvVauWypfK3ccjR47ktly5cmV4enriwIEDua81atRI3Z2UcnJWkacHZNu7d6+6URcWFgbJf+3btw/NmjXDtm3bIPUEBgYiNjZWlbt+q1q1qroh9ldbQQr3nhYtUL9SJdXs2bg4zFi/HnaHA4/36gUfT08kpaZi/tatOBYdjQohIWhRvTqmr1uHNwcPxtbff8fSq5dTAb6+eKpPH0xYsgTRFy+q+ro2aqSuLpZfjQBqhobi/jZt1HvR8fGYuWGDaqNn06b4ZvFi9frgu+5CTEIC1vyBz/VcCirCNVvdEH5Xf3gFBCNm/2acO7wD/uWqIPyufrnNXzx1BCfWzYNvSDlUbnM37FmZOLFhHlITYlWZ4PD6KN/4LiSeO4UTGxbAYctC5bZ9AF3HiQ3zVZk694zGgfnfonjZiqo93e5A3MkDiNyyVJWTzcPXH7XvHoEDC75DemKCeq1m9yHwCS4DW0YaovZsRMLpo6jTZxR+XzkDKfHnEFS5NkpUrInfV8z4W6sUlHDlBvW58+chN+fkJlJQUJDqQ2JSEjIzMtS6lycdZO3L/3LsyD0J2eT+ihxzwcHB6jiTTcqlpKaqm1KSk8x5EiAqKirPk0fyuGRUdHTueKWsh4cHYuPiVF8krynHtrObq4UrfpBL/vDw8NwubN26VR3r0jf5uVWrVqrPERERio28t3nzZjRv3lw9ciY/i0/Kli2brx8KfYT71VdfoXXr1jh58qR6rKJnz57Ys2cPjh49itq1a2cfRMHB6k7twYMHUbNmTfVahQoVFKRvvvlGLbCHHnpILY558+ahZMmSSrKXLl3C/PnzMWTIEEydOhUtW7ZEpUqV1LN7Z86cUYtM7i5Wr15d7fN3C6MghfvB8OFKemv378fdzZrheEwM/jd/Ppa99RYmL18OTzc3PNSxI7q9+qoS7ojOnTHmiy9wbPJkRMXHo9P48UrQI7t0wYv33Ye+b7+N/ZGRsJrN2Pjhh0hISkLPN95QB1X3xo3x5N13Y9LSpejSsCEcuo4xn3+Ote+/j0e/+AInz53D8rffxoMffqjq/rutoITbdNjLcPP0QXzEQdTs8RBWffCoEmuLEa9hx9QPVXeS42Nw6cwxdH3te5zZuQZunr4IqFANy98egeCqDdBqzFs4uuoXlK3fCleiI7H1+3fQ+rH3lIjnv9AXtvRU3P3+HCx8eQDK1GmJBgPH4tCiKajYqoeqV7Wj6yhduxnaPvkRNk96Hae3r1JtS5vR+35DVloKanZ/ECveG4MmQ55H7LE9qo4ur3yLyM1L8PvKmYYLNzExUQUfIgZ5ZtfTw0OJQ4kzJUUFJJLvlGNMpHAhNha1a9VSv0tgcujwYZQtU0Y9liVbTlk5tmJiYtRxI4KSQKVevXq545OnKORYzZGRHJNyk1xuZslrctxKAPR3svojKFcLd8WKFSqIk5taOdsPP/yAxo0bIyQkBFOmTEGbNm3U7yJW6XuTJk3w3XffKaecOnVKjXnAgAGqnr/abquUwuTJkzFy5EgVif3000/o1auXGqQ819a167WHww8fPqwmvmPHjrljFmEuXLhQnYV69+6tADoj3JwKJGK+ePFinsnID+jNPqWQ300zEe7puDh8uXAhAnx8MPX55/HABx8o4fZ7+23EXrmChW+8gf/Ono3E1NRc4R785htkZmVh9GefYc/Jk5j10kvw9vTE899+q4Rbu0IFTHv+eZyKjcUbU6di94kTSrgD2rTBkI8+QpkSJTDl2WfRcfx4jOvXD+WDg5Xs/by98db06TcMSApKuPd8tACbJ7+JC0d2qUgx7XI8SlSsgSYPPo85Y7vl9qla54EIDq+HDV+8oB5Ta/LgOOya/gnaPvkhzh/ejsPLpsHq6YNe787Er0/3UMINqdoAcSf2Y/1n4/IIt2aPIVj+zsir5Wdh/rg+sGWmo9WYt1WEHVK1PjZPeiNXuNu+fxeXzh5Hi9Fv4tLpozi1bYUS7Zr/PoFub0zB3Gd6ITMt+V8TbtOmTSFPCe3Zuxd169TBlStXcoUrgYwELCIOCTokmhXhynElUaAcCzVq1MgVrshPImWJ/KSsyPivhCvv5wRCsrPUI8emiFmELDKXvjjzAQWjhSvOkUh/2LBh2L59ex7h3nXXXVi3bh0efPDBGz45cVsKVyZq7ty5asLljCuJcHmmTTY5A0lEKmcgeU0mTl4TQLJ4JEr9//bOPaiK8wzjD3gZCmjgaAUdQJl4QaqiMOKFxpA6UceYogxghMQxbbWKJobqpCogajKxSMZbqjYR7cQYNU7j5YiKGKOjUZIARoOomahTjJk4MUVaL1RR6DyvLiPVnHNwwOW47/cPDrvst9+zu799vvd735VvbU4N3BG4hOrf9+7FqOhoPNWrF2bm5gpwf79kibj2NWlpeCknR2BoONyvV63ClsOHUX3rFpbb7cidPh0/VlZidX6+AHfiiBHinCVP0ctLIErgMmQwbeVKjB40SFzu2IULwXDElowMBPj7C+RPnj9vCnADwqIw6HcZ+PfFcpw9aMd3JfsRFBUr8Cv/4k7oqWhdNvomToOHhye+/CC77jw9PD0xInMtvt62WlwoW9yirdj++hgB7n//cxlP/noUPslJRczE+XUO1wBubU2N7L8r60UwtDE8PRc7574ox9y9YAJu37whDverzX/F9YqLGPLKIhRvWCwvh6dS34JfcDec3rMR3x7Y4lC7pgopGA6XwOVspqi4GOE9e8qzZDjciooK/LO8XAAT0KGDOE8aHc4cOcvjApQU9nh5icNluIDPFY8RFhYmz92DgEsz5OfvLyGE4OBg8FwM4PJciktK0Kd3b5fSKc0ALsOTPGf2zZeV4XD5MuJLJi4uTp6jn2tuC9zNmzeDNwxvDL41+W82OlfeAJy6REVFwahI4dupX79+ckOxsi0lJcUtgftMRAQuX72KK1VVyFy3TmKoBG7VzZtS0bVs2zasKShA/+7d6znclEWLMGfsWGzYvx9tfXwQEx6OlXl5AtytmZnYfOgQ/Hx8BLTPz5snP+mof7h8GZ1sNozLzpZ92dJGj8aQPn0wZsECh8DgxqZwuARoa9+2uFV1DaExzyEy6RV8kjMNPu0DMfDldBxc/rqcF11q34RUtPZpi8/Xvim/87EF4HrlTxg25z2Zzpd/USDOd8zbdmyd8bwAt/LCOVwuPy3xXMZu7bOTJKRgAJfHGbM4DztmJaDLoBHoOSIFpVvfQ/jI8ThVsBHnPssT4P7Cr72EPc4XfYrCtW9I/536DEbMpPmwz07EjSuVpgOXOamEHF3ntatX5flgqIG/p5Nl5RrjvYTg9aoqnDlzBiHBwTL99/b2llAEnzeCl6mQhKetXTuB9IOAyyKE0C5d6ooQGMozgEtoHzt+XPoivJ01M4A7ZcoUmV3TzHH8BnCpA8eRnJwsOjxWwKVLZZx10qRJstDlLKTA7bt27RLgstERjxs3DkVFRTItYF4c39hMik5KSqoXwzWEay4hhe8rKvDuzp2ovn1b4rF+vr4C3OTsbPQODcWwyEhMXbHiPuDSjU4eORKRXbviD0uX4s+JieJ2b1RXY0VqqkCabfzQoeKQo3v0QHJsLCYuW4a1aWnYVlgoC2dsXEyL7t4dM3JznT0TTQLcVl7e+O1fPkbBWxNx5ccLePrVHJw9lAePFp73hRQ69hqAvglTsXveeLRo2RrPvbkB9lmJ6J8yA63b+OHw3zLQsfdARCa9ip2ZyXXALd2+GsPTV6NdaDg2TY6tB9zgyFhExE/GzrkpGDItWxbBKr8/i3ahPdE2sDP2LpyM4ZlrULz+bXi2bIXIF6Yjf8HLopWtcw/EvrYYO+aMRbWDcAL3fRQOl2EEw5ywaILADQkJwYmyMgEfDQvjvVwH4XNEV/fEXXdHs8PYLtdUjJACZ5dcTKL7bWhIgf0TWhEslvG8U2XoqJkB3LS0NBkvZ8eRkZH1Yrh8GdHB08z9nMt1K4e7ZMkScbB8+3JVkJkEjDUxfGC8VZi9YMSajBguK9g4JWIYge3gwYNyU/AY+fn5UlbMY3JBjtMcwpzb+dZmI5w5lWpOMVzjRjSAS6BWXruGHVlZmLt+vYDUCCkwhsvtPYKCMCM+HsPS0wWyBC4zH9jmf/ih/CSUO3fogENlZXUxXMI1KyUFo7KypAzBbODyPLsMeBY9nn1Bprk1t27is1UZ+GX3CJmy/+tsmYyFDvfoR++gX9JUdOw1EKipxTkuVBVsFNc7YPwstAkIkuKKY/9YhR9OfF4PuAE9o/CbGcvx0V3gxvxxgcRkmc1w/ONVkq0Ql70FeRnjJBuBjnbk/PWwz07A0JnvwIjhPvOnpbhw9AC+PbCt2QD35KlTsrBFAHQOCZHFZALVCClwoewnlgmzerJVK3nWSk+cQLe7WUDUnWaHYT0uejGUYMRd6ZAZx/2yqKiulJZwtPn7C8jpDNn4ARc6WZb2+3h7i6Mm7I3tZgCXMDU+McB1IbvdXrdoRmdL4NKJ898cp+FwJ0yYIGPh7zmzvnex8N5xuBVwnV2A5rC9KbMUmsP4GnoOTRFSaOg5uOv+TeVw3VWP/z/vxna4j0IXBW4jq6zArS+oAvfhbzAF7qMNKTz8lXL9LxW4rmvl0p4KXAWuSzeKCzspcBW4LtwmskuTVJq52rmZ+ylwFbiNdf8pcBW4rt5LClz9WpjcKxpScPWRuX8/Be7jB1yCkVlRXOQ3pbSXq5tcpWQGwOPSmMDNgD7zDR3l5BnjfePAAewuLUUN/1sUB0nTbqlPbS1a+vri/aQkPGmzOR3CpXUzcbH0CKqqa9CCH4WV5t5fkHM66Afu4IHbNbXwbuWJ9oGdEPDaJng4+R6u1T5Afu83HhxpfPqbbyRfn9lIrqSbPdz1cv2vmOHBrBBmZAQGBLj+hw72dNnhMg/28JEjkjwdHx/fKJ2bfZA9e/YIaGMGDxbwOmv5J08ifdMmtPD2RpuuXZ3t7lbbK0pK4Ne+PbZPnYq2d9PsHA3gux0rcHT7GnR+wgu/CrjzcRSrtqILV3HpWjUiYkeiy0t3CjccNb7oWXrrrh/wdza+e7czdMfKLqaAOms0dKw05TPJlC0zG6/Nvn37BLhPDxniEh9cOV+XgcuDsVb70/37MfhuTqgrHTTnffhVoej+/eVDOo7K/IwxsIhhY2Eh1h07htrAwOY8tAafm+3iRcwdPRq9goKknNNZu32jCqfs78Lzq63o5uf8YXJ2PHfefvxSNbwHJiAsbooUULjSWJhAN8efj2tjib6/zQZX/z8wKUkuK5NZ9L3fcTBDHylfLi6WghE63MZqDQJuY3Wqx1EFVAFVwIoKKHCteNV1zKqAKmCKAgpcU2TXTlUBVcCKCihwrXjVdcyqgCpgigIKXFNk105VAVXAigoocK141XXMqoAqYIoCClxTZNdOVQFVwIoKKHCteNV1zKqAKmCKAgpcU2TXTlUBVcCKCihwrXjVdcyqgCpgigIKXFNk105VAVXAigoocK141XXMqoAqYIoCClxTZNdOVQFVwIoKKHCteNV1zKqAKmCKAgpcU2TXTlUBVcCKCihwrXjVdcyqgCpgigIKXFNk105VAVXAigoocK141XXMqoAqYIoCClxTZNdOVQFVwIoKKHCteNV1zKqAKmCKAgpcU2TXTlUBVcCKCihwrXjVdcyqgCpgigIKXFNk105VAVXAigoocK141XXMqoAqYIoCBO7/ALtE8Dqf03W0AAAAAElFTkSuQmCC');



-- agency

SELECT (current_setting('custom.plugins') ) AS plugins \gset
\if :split_part(:plugins, ',')
    \echo plugins: :split_part(:plugins, ',')

SELECT ('true' = current_setting('custom.is_agency')) AS is_agency \gset
\if :is_agency
    \echo starting agency SQL
    \i /agency.db.sql
    \echo finished agency SQL
\endif















































