#!/usr/bin/env powershell
$INIT_INSTALL_VERSION="v0.0.1"
$INIT_APP_NAME = "marioviajes"
$INIT_APP_VERSION = "1.5.0"
$INIT_WEBSITE_NAME = "Mario Viajes"
$INIT_WEBSITE_EMAIL = "contact@marioviajes.com"
$INIT_ADMIN_FNAME = "Mario"
$INIT_ADMIN_LNAME = "Viajes"
$INIT_WEBSITE_DOMAIN = "marioviajes.com"
$INIT_DEFAULT_EMAIL = "admin@localhost.local"
$INIT_DEFAULT_PASSWORD = "1qaz"
$INIT_TPL_VER = "v1"
$INIT_POSTGRES_DEFAULT_USER = "cms"
$INIT_POSTGRES_DEFAULT_PASSWORD = "1qaz"
$INIT_POSTGRES_DEFAULT_DB = "main"
$INIT_POSTGRES_DEFAULT_CONNECTIONS = "main,agency"
$INIT_PGADMIN_DEFAULT_EMAIL = "admin@localhost.local"
$INIT_PGADMIN_DEFAULT_PASSWORD = "1qaz"
$INIT_REDIS_DEFAULT_PASSWORD = "1gzHwbgfwR"
$CMS_HUB_VERSION="1650274457"
$CMS_DB_VERSION="1650274457"
$CMS_BUCKET_VERSION="1650274457"
$CMS_FRONTEND_PROXY_VERSION="1650274457"
$CMS_FRONTEND_VERSION="1650274457"
$CMS_ADMIN_PROXY_VERSION="1650274457"
$CMS_ADMIN_SYSTEM_VERSION="1650274457"
$PWD=$pwd.Path

if (($INSTALL_VERSION = Read-Host "Install version (Enter for default:  $INIT_INSTALL_VERSION)") -eq '') { $INSTALL_VERSION = $INIT_INSTALL_VERSION }
if (($APP_NAME = Read-Host "App name (Enter for default:  $INIT_APP_NAME)") -eq '') { $APP_NAME = $INIT_APP_NAME }
if (($APP_VERSION = Read-Host "App version (Enter for default:  $INIT_APP_VERSION)") -eq '') { $APP_VERSION = $INIT_APP_VERSION }
if (($DEFAULT_EMAIL = Read-Host "Admin Email (Enter for default: $INIT_DEFAULT_EMAIL)") -eq '') { $DEFAULT_EMAIL = $INIT_DEFAULT_EMAIL }
if (($DEFAULT_PASSWORD = Read-Host "Admin Password (Enter for default: $INIT_DEFAULT_PASSWORD)") -eq '') { $DEFAULT_PASSWORD = $INIT_DEFAULT_PASSWORD }
if (($WEBSITE_NAME = Read-Host "Website name (Enter for default: $INIT_WEBSITE_NAME)") -eq '') { $WEBSITE_NAME = $INIT_WEBSITE_NAME }
if (($WEBSITE_EMAIL = Read-Host "Website email (Enter for default: $INIT_WEBSITE_EMAIL)") -eq '') { $WEBSITE_EMAIL = $INIT_WEBSITE_EMAIL }
if (($ADMIN_FNAME = Read-Host "Admin first name (Enter for default: $INIT_ADMIN_FNAME)") -eq '') { $ADMIN_FNAME = $INIT_ADMIN_FNAME }
if (($ADMIN_LNAME = Read-Host "Admin last name (Enter for default: $INIT_ADMIN_LNAME)") -eq '') { $ADMIN_LNAME = $INIT_ADMIN_LNAME }
if (($WEBSITE_DOMAIN = Read-Host "Website domain (Enter for default: $INIT_WEBSITE_DOMAIN)") -eq '') { $WEBSITE_DOMAIN = $INIT_WEBSITE_DOMAIN }
if (($TPL_VER = Read-Host "App template E.G. v1 (Enter for default:  $INIT_TPL_VER)") -eq '') { $TPL_VER = $INIT_TPL_VER }

if (($REDIS_DEFAULT_PASSWORD = Read-Host "Redis password (Enter for default:  $INIT_REDIS_DEFAULT_PASSWORD)") -eq '') { $REDIS_DEFAULT_PASSWORD = $INIT_REDIS_DEFAULT_PASSWORD }
if (($POSTGRES_DEFAULT_USER = Read-Host "Postgres user (Enter for default:  $INIT_POSTGRES_DEFAULT_USER)") -eq '') { $POSTGRES_DEFAULT_USER = $INIT_POSTGRES_DEFAULT_USER }
if (($POSTGRES_DEFAULT_PASSWORD = Read-Host "Postgres password (Enter for default: $INIT_POSTGRES_DEFAULT_PASSWORD)") -eq '') { $POSTGRES_DEFAULT_PASSWORD = $INIT_POSTGRES_DEFAULT_PASSWORD }
if (($POSTGRES_DEFAULT_DB = Read-Host "Postgres Database name (Enter for default: $INIT_POSTGRES_DEFAULT_DB)") -eq '') { $POSTGRES_DEFAULT_DB = $INIT_POSTGRES_DEFAULT_DB }
if (($POSTGRES_DEFAULT_CONNECTIONS = Read-Host "Postgres Databases (Enter for default: $INIT_POSTGRES_DEFAULT_CONNECTIONS)") -eq '') { $POSTGRES_DEFAULT_CONNECTIONS = $INIT_POSTGRES_DEFAULT_CONNECTIONS }

if (($PGADMIN_DEFAULT_EMAIL = Read-Host "PgAdmin email (Enter for default: $INIT_PGADMIN_DEFAULT_EMAIL)") -eq '') { $PGADMIN_DEFAULT_EMAIL = $INIT_PGADMIN_DEFAULT_EMAIL }
if (($PGADMIN_DEFAULT_PASSWORD = Read-Host "PgAdmin password (Enter for default: $INIT_PGADMIN_DEFAULT_PASSWORD)") -eq '') { $PGADMIN_DEFAULT_PASSWORD = $INIT_PGADMIN_DEFAULT_PASSWORD }

$env:APP_NAME=$APP_NAME
$env:INSTALL_VERSION=$INSTALL_VERSION
$env:APP_VERSION=$APP_VERSION
$env:DEFAULT_EMAIL=$DEFAULT_EMAIL
$env:DEFAULT_PASSWORD=$DEFAULT_PASSWORD
$env:WEBSITE_NAME=$WEBSITE_NAME
$env:WEBSITE_EMAIL=$WEBSITE_EMAIL
$env:ADMIN_FNAME=$ADMIN_FNAME
$env:ADMIN_LNAME=$ADMIN_LNAME
$env:WEBSITE_DOMAIN=$WEBSITE_DOMAIN
$env:APP_DOMAIN=$APP_DOMAIN
$env:TPL_VER=$TPL_VER

$env:REDIS_DEFAULT_PASSWORD=$REDIS_DEFAULT_PASSWORD

$env:POSTGRES_DEFAULT_USER=$POSTGRES_DEFAULT_USER
$env:POSTGRES_DEFAULT_PASSWORD=$POSTGRES_DEFAULT_PASSWORD
$env:POSTGRES_DEFAULT_DB=$POSTGRES_DEFAULT_DB
$env:POSTGRES_DEFAULT_CONNECTIONS=$POSTGRES_DEFAULT_CONNECTIONS

$env:PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
$env:PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD

$env:CMS_HUB_VERSION=$CMS_HUB_VERSION
$env:CMS_DB_VERSION=$CMS_DB_VERSION
$env:CMS_BUCKET_VERSION=$CMS_BUCKET_VERSION
$env:CMS_FRONTEND_PROXY_VERSION=$CMS_FRONTEND_PROXY_VERSION
$env:CMS_FRONTEND_VERSION=$CMS_FRONTEND_VERSION
$env:CMS_ADMIN_PROXY_VERSION=$CMS_ADMIN_PROXY_VERSION
$env:CMS_ADMIN_SYSTEM_VERSION=$CMS_ADMIN_SYSTEM_VERSION

$env:PWD=$PWD

echo $PWD

echo "$INSTALL_VERSION"
echo "$APP_NAME"
echo "$APP_VERSION"
echo "$DEFAULT_EMAIL"
echo "$DEFAULT_PASSWORD"
echo "$WEBSITE_NAME"
echo "$WEBSITE_EMAIL"
echo "$ADMIN_FNAME"
echo "$ADMIN_LNAME"
echo "$WEBSITE_DOMAIN"
echo "$APP_DOMAIN"
echo "$TPL_VER"
echo "$REDIS_DEFAULT_PASSWORD"
echo "$POSTGRES_DEFAULT_USER"
echo "$POSTGRES_DEFAULT_PASSWORD"
echo "$POSTGRES_DEFAULT_DB"
echo "$POSTGRES_DEFAULT_CONNECTIONS"
echo "$PGADMIN_DEFAULT_EMAIL"
echo "$PGADMIN_DEFAULT_PASSWORD"
echo "$CMS_HUB_VERSION"
echo "$CMS_DB_VERSION"
echo "$CMS_BUCKET_VERSION"
echo "$CMS_FRONTEND_PROXY_VERSION"
echo "$CMS_FRONTEND_VERSION"
echo "$CMS_ADMIN_PROXY_VERSION"
echo "$CMS_ADMIN_SYSTEM_VERSION"

echo "**************** Starting Services *****************"

Write-Output "Login in to docker"

Get-Content ../secrets/dockerpass.txt | docker login --username cmsbot --password-stdin

echo "..\versions\$INSTALL_VERSION\base.yaml"

"docker-compose -f ..\versions\$INSTALL_VERSION\base.yaml up -d" | cmd

echo "**************** Services Started *****************"