apiVersion: v1
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - MY_IP_RANGE
kind: ConfigMap
metadata:
  name: metallbconfig
  namespace: metallb-system
  selfLink: /api/v1/namespaces/metallb-system/configmaps/config