apiVersion: v1
kind: Config
clusters:
- name: "crm-cluster"
  cluster:
    server: "https://localhost:30443/k8s/clusters/c-rhp26"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpRENDQ\
      VM2Z0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQTdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRXdIa\
      GNOTWpBdwpPREE1TVRreU1ERTJXaGNOTXpBd09EQTNNVGt5TURFMldqQTdNUnd3R2dZRFZRUUtFe\
      E5rZVc1aGJXbGpiR2x6CmRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR\
      1Z1WlhJdFkyRXdXVEFUQmdjcWhrak8KUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVJHTVkyaWxPUGtUK\
      1lSQld4aTlrdWxnNWQzbFo5ZWJKUTNILytIVTVjRApDOUE3cUZqNUNlNElyZVJxN3FJTzZJNUY2Q\
      nBNeTNsZDhESVRUTXZSUEx5aW95TXdJVEFPQmdOVkhROEJBZjhFCkJBTUNBcVF3RHdZRFZSMFRBU\
      UgvQkFVd0F3RUIvekFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBMlVRYUdIREsKR0NJQlhSMUkvV\
      0plU3RBU2NTWkdVc3dvN3Y5UHRBOEhmMzhDSUhBL1F3OGh3Z0Rqbkk0WVlZaEgvY1Bvb2ozeQpuZ\
      Td4TmNkaGJxQ2dmcE1LCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0="

users:
- name: "crm-cluster"
  user:
    token: "kubeconfig-user-zk4ns:thnsrrnt7hdlvtm76ptggqhjmfns8jhfnxqm98jlt9h8lgpgxd48dm"

contexts:
- name: "crm-cluster"
  context:
    user: "crm-cluster"
    cluster: "crm-cluster"

current-context: "crm-cluster"

