name: Build Frontend Api

env:
  DOCKER_IMAGE: 'dispeakble/crm-frontend-api:'
  WORKING_DIR: core/frontend/api

on:
  pull_request:
    paths:
      - "${{ env.WORKING_DIR }}/**"
    branches: [ master ]
    types: [opened, synchronize, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build the Docker image
        working-directory: ${{ env.WORKING_DIR }}
        run: docker build . --file Dockerfile --tag ${{ env.DOCKER_IMAGE }}${{ github.event.pull_request.head.sha }}
      - name: Push docker image
        run: docker push ${{ env.DOCKER_IMAGE }}${{ github.event.pull_request.head.sha }}
