name: Build Frontend Proxy

env:
  TIMESTAMP: $(date +%s)

on:
  pull_request_target:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  pull_request:
    paths: 
      - 'core/frontend/proxy/**'
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker login
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - name: Build the Frontend Proxy Docker image
        working-directory: core/frontend/proxy
        run: docker build . --file Dockerfile --tag dispeakble/crm-frontend-proxy:$TIMESTAMP
      - name: Push docker image
        run: docker push dispeakble/crm-frontend-proxy:$TIMESTAMP
      - name: Report
        if: failure() && github.event.action != 'push'
        with: fancy/commenter@v1
          message: |
            Some checks have failed.
