name: Clear CMS Ci

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Change directory to frontend
      run: cd core/frontend/api
    - name: Build the Frontend Docker image
      run: docker build . --file Dockerfile --tag dispeakble/crm-frontend-api:$(date +%s)
    - name: Push the Frontend Docker image
      run: docker build . --file Dockerfile --tag dispeakble/crm-frontend-api:$(date +%s)
