name: Build Hub

env:
  TIMESTAMP: $(date +%s)

on:
  pull_request_target:
    types:
      - opened
  pull_request:
    paths: 
      - 'core/hub/api/**'
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Build the Hub Docker image
        working-directory: ./core/hub
        run: docker build . --file Dockerfile --tag dispeakble/crm-hub:$TIMESTAMP
      - name: Push docker image
        run: docker push dispeakble/crm-hub:$TIMESTAMP
