name: Build System

env:
  TIMESTAMP: $(date +%s)

on:
  pull_request_target:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  pull_request:
    paths: 
      - 'core/system/**'
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Build the System Docker image
        working-directory: ../core/system
        run: docker build . --file Dockerfile --tag dispeakble/crm-system:$TIMESTAMP
      - name: Push docker image
        run: docker push dispeakble/crm-system:$TIMESTAMP
