name: Build Db

env:
  TIMESTAMP: $(date +%s)

on:
  pull_request_target:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  pull_request:
    paths: 
      - 'plugins/dosido/db/**'
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Build the Db Docker image
        working-directory: ./plugins/dosido/db
        run: docker build . --file Dockerfile --tag dispeakble/crm-db:$TIMESTAMP
      - name: Push docker image
        run: docker push dispeakble/crm-db:$TIMESTAMP
