name: Build Bucket

env:
  TIMESTAMP: $(date +%s)

on:
  pull_request_target:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  pull_request:
    paths: 
      - 'plugins/dosido/bucket/**'
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - name: Build the Bucket Proxy Docker image
        working-directory: plugins/dosido/bucket
        run: docker build . --file Dockerfile --tag dispeakble/crm-bucket:$TIMESTAMP
      - name: Push docker image
        run: docker push dispeakble/crm-bucket:$TIMESTAMP
      - name: Report
        if: failure() && github.event.action != 'push'
        with: fancy/commenter@v1
          message: Some checks have failed.
