name: Build Backend Proxy

env:
  TIMESTAMP: $(date +%s)

on:
  pull_request_target:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  pull_request:
    paths: 
      - 'core/proxy/**'
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Build the Backend Proxy Docker image
        uses: actions/build-frontend@v1
        working-directory: core/proxy
        run: docker build . --file Dockerfile --tag dispeakble/crm-proxy:$TIMESTAMP
      - name: Push docker image
        run: docker push dispeakble/crm-proxy:$TIMESTAMP
