name: Run Frontend Lint

env:
  WORKING_DIR: core/frontend/api

on:
  pull_request:
    paths:
      - "core/frontend/api/**"
    branches: [ master ]
    types: [opened, synchronize, reopened, synchronize]

jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('yarn.lock.json') }}
          restore-keys: npm-
      - name: Install modules
        working-directory: ${{ env.WORKING_DIR }}
        run: yarn
      - name: Run lint
        working-directory: ${{ env.WORKING_DIR }}
        run: yarn run lint:prod
